/*@ okeys.h, generated by ./mk-okey-map.pl on Fri Sep 23 20:16:03 2016.
 *@ See accmacvar.c for more */

static char const a_amv_var_names[] = {
   /* 0. [0]+16 on-compose-enter */
   'o','n','-','c','o','m','p','o','s','e','-','e','n','t','e','r','\0',
   /* 1. [17]+16 on-compose-leave */
   'o','n','-','c','o','m','p','o','s','e','-','l','e','a','v','e','\0',
   /* 2. [34]+12 compose-from */
   'c','o','m','p','o','s','e','-','f','r','o','m','\0',
   /* 3. [47]+14 compose-sender */
   'c','o','m','p','o','s','e','-','s','e','n','d','e','r','\0',
   /* 4. [62]+10 compose-to */
   'c','o','m','p','o','s','e','-','t','o','\0',
   /* 5. [73]+10 compose-cc */
   'c','o','m','p','o','s','e','-','c','c','\0',
   /* 6. [84]+11 compose-bcc */
   'c','o','m','p','o','s','e','-','b','c','c','\0',
   /* 7. [96]+15 compose-subject */
   'c','o','m','p','o','s','e','-','s','u','b','j','e','c','t','\0',
   /* 8. [112]+19 add-file-recipients, a_AMV_VF_BOOL */
   'a','d','d','-','f','i','l','e','-','r','e','c','i','p','i','e','n','t','s','\0',
   /* 9. [132]+18 agent-shell-lookup */
   'a','g','e','n','t','-','s','h','e','l','l','-','l','o','o','k','u','p','\0',
   /* 10. [151]+6 allnet, a_AMV_VF_BOOL */
   'a','l','l','n','e','t','\0',
   /* 11. [158]+6 append, a_AMV_VF_BOOL */
   'a','p','p','e','n','d','\0',
   /* 12. [165]+3 ask, a_AMV_VF_BOOL */
   'a','s','k','\0',
   /* 13. [169]+8 askatend, a_AMV_VF_BOOL */
   'a','s','k','a','t','e','n','d','\0',
   /* 14. [178]+9 askattach, a_AMV_VF_BOOL */
   'a','s','k','a','t','t','a','c','h','\0',
   /* 15. [188]+6 askbcc, a_AMV_VF_BOOL */
   'a','s','k','b','c','c','\0',
   /* 16. [195]+5 askcc, a_AMV_VF_BOOL */
   'a','s','k','c','c','\0',
   /* 17. [201]+7 asksign, a_AMV_VF_BOOL */
   'a','s','k','s','i','g','n','\0',
   /* 18. [209]+6 asksub, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'a','s','k','s','u','b','\0',
   /* 19. [216]+34 attachment-ask-content-description, a_AMV_VF_BOOL */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','\0',
   /* 20. [251]+34 attachment-ask-content-disposition, a_AMV_VF_BOOL */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','i','s','p','o','s','i','t','i','o','n','\0',
   /* 21. [286]+25 attachment-ask-content-id, a_AMV_VF_BOOL */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','i','d','\0',
   /* 22. [312]+27 attachment-ask-content-type, a_AMV_VF_BOOL */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','t','y','p','e','\0',
   /* 23. [340]+8 attrlist */
   'a','t','t','r','l','i','s','t','\0',
   /* 24. [349]+7 autobcc */
   'a','u','t','o','b','c','c','\0',
   /* 25. [357]+6 autocc */
   'a','u','t','o','c','c','\0',
   /* 26. [364]+12 autocollapse, a_AMV_VF_BOOL */
   'a','u','t','o','c','o','l','l','a','p','s','e','\0',
   /* 27. [377]+9 autoprint, a_AMV_VF_BOOL */
   'a','u','t','o','p','r','i','n','t','\0',
   /* 28. [387]+10 autothread, a_AMV_VF_BOOL */
   'a','u','t','o','t','h','r','e','a','d','\0',
   /* 29. [398]+8 autosort */
   'a','u','t','o','s','o','r','t','\0',
   /* 30. [407]+4 bang, a_AMV_VF_BOOL */
   'b','a','n','g','\0',
   /* 31. [412]+19 batch-exit-on-error, a_AMV_VF_BOOL */
   'b','a','t','c','h','-','e','x','i','t','-','o','n','-','e','r','r','o','r','\0',
   /* 32. [432]+12 bind-timeout, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'b','i','n','d','-','t','i','m','e','o','u','t','\0',
   /* 33. [445]+11 bsdannounce, a_AMV_VF_BOOL */
   'b','s','d','a','n','n','o','u','n','c','e','\0',
   /* 34. [457]+9 bsdcompat, a_AMV_VF_BOOL */
   'b','s','d','c','o','m','p','a','t','\0',
   /* 35. [467]+8 bsdflags, a_AMV_VF_BOOL */
   'b','s','d','f','l','a','g','s','\0',
   /* 36. [476]+11 bsdheadline, a_AMV_VF_BOOL */
   'b','s','d','h','e','a','d','l','i','n','e','\0',
   /* 37. [488]+7 bsdmsgs, a_AMV_VF_BOOL */
   'b','s','d','m','s','g','s','\0',
   /* 38. [496]+8 bsdorder, a_AMV_VF_BOOL */
   'b','s','d','o','r','d','e','r','\0',
   /* 39. [505]+7 COLUMNS, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV */
   'C','O','L','U','M','N','S','\0',
   /* 40. [513]+12 charset-7bit */
   'c','h','a','r','s','e','t','-','7','b','i','t','\0',
   /* 41. [526]+12 charset-8bit */
   'c','h','a','r','s','e','t','-','8','b','i','t','\0',
   /* 42. [539]+20 charset-unknown-8bit */
   'c','h','a','r','s','e','t','-','u','n','k','n','o','w','n','-','8','b','i','t','\0',
   /* 43. [560]+3 cmd */
   'c','m','d','\0',
   /* 44. [564]+14 colour-disable, a_AMV_VF_BOOL */
   'c','o','l','o','u','r','-','d','i','s','a','b','l','e','\0',
   /* 45. [579]+12 colour-pager, a_AMV_VF_BOOL */
   'c','o','l','o','u','r','-','p','a','g','e','r','\0',
   /* 46. [592]+3 crt, a_AMV_VF_POSNUM */
   'c','r','t','\0',
   /* 47. [596]+9 customhdr, a_AMV_VF_NOCNTRLS */
   'c','u','s','t','o','m','h','d','r','\0',
   /* 48. [606]+4 DEAD, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'D','E','A','D','\0',
   /* 49. [611]+9 datefield */
   'd','a','t','e','f','i','e','l','d','\0',
   /* 50. [621]+23 datefield-markout-older */
   'd','a','t','e','f','i','e','l','d','-','m','a','r','k','o','u','t','-','o','l','d','e','r','\0',
   /* 51. [645]+5 debug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'd','e','b','u','g','\0',
   /* 52. [651]+29 disposition-notification-send, a_AMV_VF_BOOL */
   'd','i','s','p','o','s','i','t','i','o','n','-','n','o','t','i','f','i','c','a','t','i','o','n','-','s','e','n','d','\0',
   /* 53. [681]+3 dot, a_AMV_VF_BOOL */
   'd','o','t','\0',
   /* 54. [685]+20 dotlock-ignore-error, a_AMV_VF_BOOL */
   'd','o','t','l','o','c','k','-','i','g','n','o','r','e','-','e','r','r','o','r','\0',
   /* 55. [706]+6 EDITOR, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'E','D','I','T','O','R','\0',
   /* 56. [713]+9 editalong, a_AMV_VF_BOOL */
   'e','d','i','t','a','l','o','n','g','\0',
   /* 57. [723]+11 editheaders, a_AMV_VF_BOOL */
   'e','d','i','t','h','e','a','d','e','r','s','\0',
   /* 58. [735]+8 emptybox, a_AMV_VF_BOOL */
   'e','m','p','t','y','b','o','x','\0',
   /* 59. [744]+10 emptystart, a_AMV_VF_BOOL */
   'e','m','p','t','y','s','t','a','r','t','\0',
   /* 60. [755]+8 encoding */
   'e','n','c','o','d','i','n','g','\0',
   /* 61. [764]+6 escape */
   'e','s','c','a','p','e','\0',
   /* 62. [771]+10 expandaddr */
   'e','x','p','a','n','d','a','d','d','r','\0',
   /* 63. [782]+10 expandargv */
   'e','x','p','a','n','d','a','r','g','v','\0',
   /* 64. [793]+8 features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'f','e','a','t','u','r','e','s','\0',
   /* 65. [802]+5 flipr, a_AMV_VF_BOOL */
   'f','l','i','p','r','\0',
   /* 66. [808]+6 folder, a_AMV_VF_VIP */
   'f','o','l','d','e','r','\0',
   /* 67. [815]+16 -folder-resolved, a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   '-','f','o','l','d','e','r','-','r','e','s','o','l','v','e','d','\0',
   /* 68. [832]+11 folder-hook */
   'f','o','l','d','e','r','-','h','o','o','k','\0',
   /* 69. [844]+11 followup-to, a_AMV_VF_BOOL */
   'f','o','l','l','o','w','u','p','-','t','o','\0',
   /* 70. [856]+18 followup-to-honour */
   'f','o','l','l','o','w','u','p','-','t','o','-','h','o','n','o','u','r','\0',
   /* 71. [875]+21 forward-as-attachment, a_AMV_VF_BOOL */
   'f','o','r','w','a','r','d','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 72. [897]+4 from */
   'f','r','o','m','\0',
   /* 73. [902]+9 fullnames, a_AMV_VF_BOOL */
   'f','u','l','l','n','a','m','e','s','\0',
   /* 74. [912]+10 fwdheading */
   'f','w','d','h','e','a','d','i','n','g','\0',
   /* 75. [923]+4 HOME, a_AMV_VF_IMPORT|a_AMV_VF_NODEL|a_AMV_VF_VIP|a_AMV_VF_ENV */
   'H','O','M','E','\0',
   /* 76. [928]+6 header, a_AMV_VF_BOOL|a_AMV_VF_I3VAL|a_AMV_VF_VIP */
   'h','e','a','d','e','r','\0',
   /* 77. [935]+8 headline */
   'h','e','a','d','l','i','n','e','\0',
   /* 78. [944]+13 headline-bidi */
   'h','e','a','d','l','i','n','e','-','b','i','d','i','\0',
   /* 79. [958]+12 history-file */
   'h','i','s','t','o','r','y','-','f','i','l','e','\0',
   /* 80. [971]+13 history-gabby, a_AMV_VF_BOOL */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','\0',
   /* 81. [985]+21 history-gabby-persist, a_AMV_VF_BOOL */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','-','p','e','r','s','i','s','t','\0',
   /* 82. [1007]+12 history-size, a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM */
   'h','i','s','t','o','r','y','-','s','i','z','e','\0',
   /* 83. [1020]+4 hold, a_AMV_VF_BOOL */
   'h','o','l','d','\0',
   /* 84. [1025]+8 hostname */
   'h','o','s','t','n','a','m','e','\0',
   /* 85. [1034]+12 idna-disable, a_AMV_VF_BOOL */
   'i','d','n','a','-','d','i','s','a','b','l','e','\0',
   /* 86. [1047]+6 ignore, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','\0',
   /* 87. [1054]+9 ignoreeof, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','e','o','f','\0',
   /* 88. [1064]+12 indentprefix */
   'i','n','d','e','n','t','p','r','e','f','i','x','\0',
   /* 89. [1077]+4 keep, a_AMV_VF_BOOL */
   'k','e','e','p','\0',
   /* 90. [1082]+19 keep-content-length, a_AMV_VF_BOOL */
   'k','e','e','p','-','c','o','n','t','e','n','t','-','l','e','n','g','t','h','\0',
   /* 91. [1102]+8 keepsave, a_AMV_VF_BOOL */
   'k','e','e','p','s','a','v','e','\0',
   /* 92. [1111]+5 LINES, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV */
   'L','I','N','E','S','\0',
   /* 93. [1117]+6 LISTER, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'L','I','S','T','E','R','\0',
   /* 94. [1124]+7 LOGNAME, a_AMV_VF_IMPORT|a_AMV_VF_RDONLY|a_AMV_VF_ENV */
   'L','O','G','N','A','M','E','\0',
   /* 95. [1132]+19 line-editor-disable, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','d','i','s','a','b','l','e','\0',
   /* 96. [1152]+23 line-editor-no-defaults, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 97. [1176]+4 MAIL, a_AMV_VF_ENV */
   'M','A','I','L','\0',
   /* 98. [1181]+6 MAILRC, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'M','A','I','L','R','C','\0',
   /* 99. [1188]+4 MBOX, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'M','B','O','X','\0',
   /* 100. [1193]+12 markanswered, a_AMV_VF_BOOL */
   'm','a','r','k','a','n','s','w','e','r','e','d','\0',
   /* 101. [1206]+8 memdebug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'm','e','m','d','e','b','u','g','\0',
   /* 102. [1215]+18 message-id-disable, a_AMV_VF_BOOL */
   'm','e','s','s','a','g','e','-','i','d','-','d','i','s','a','b','l','e','\0',
   /* 103. [1234]+19 message-inject-head */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 104. [1254]+19 message-inject-tail */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 105. [1274]+5 metoo, a_AMV_VF_BOOL */
   'm','e','t','o','o','\0',
   /* 106. [1280]+24 mime-allow-text-controls, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','l','o','w','-','t','e','x','t','-','c','o','n','t','r','o','l','s','\0',
   /* 107. [1305]+28 mime-alternative-favour-rich, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','t','e','r','n','a','t','i','v','e','-','f','a','v','o','u','r','-','r','i','c','h','\0',
   /* 108. [1334]+21 mime-counter-evidence, a_AMV_VF_POSNUM */
   'm','i','m','e','-','c','o','u','n','t','e','r','-','e','v','i','d','e','n','c','e','\0',
   /* 109. [1356]+22 mimetypes-load-control */
   'm','i','m','e','t','y','p','e','s','-','l','o','a','d','-','c','o','n','t','r','o','l','\0',
   /* 110. [1379]+3 mta */
   'm','t','a','\0',
   /* 111. [1383]+13 mta-arguments */
   'm','t','a','-','a','r','g','u','m','e','n','t','s','\0',
   /* 112. [1397]+24 mta-no-default-arguments, a_AMV_VF_BOOL */
   'm','t','a','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 113. [1422]+9 mta-argv0 */
   'm','t','a','-','a','r','g','v','0','\0',
   /* 114. [1432]+13 NAIL_EXTRA_RC */
   'N','A','I','L','_','E','X','T','R','A','_','R','C','\0',
   /* 115. [1446]+17 NAIL-NO-SYSTEM-RC, a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'N','A','I','L','-','N','O','-','S','Y','S','T','E','M','-','R','C','\0',
   /* 116. [1464]+9 NAIL_HEAD */
   'N','A','I','L','_','H','E','A','D','\0',
   /* 117. [1474]+13 NAIL_HISTFILE */
   'N','A','I','L','_','H','I','S','T','F','I','L','E','\0',
   /* 118. [1488]+13 NAIL_HISTSIZE, a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM */
   'N','A','I','L','_','H','I','S','T','S','I','Z','E','\0',
   /* 119. [1502]+9 NAIL_TAIL */
   'N','A','I','L','_','T','A','I','L','\0',
   /* 120. [1512]+5 NETRC, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'N','E','T','R','C','\0',
   /* 121. [1518]+12 netrc-lookup, a_AMV_VF_BOOL */
   'n','e','t','r','c','-','l','o','o','k','u','p','\0',
   /* 122. [1531]+10 netrc-pipe */
   'n','e','t','r','c','-','p','i','p','e','\0',
   /* 123. [1542]+10 newfolders */
   'n','e','w','f','o','l','d','e','r','s','\0',
   /* 124. [1553]+7 newmail */
   'n','e','w','m','a','i','l','\0',
   /* 125. [1561]+9 outfolder, a_AMV_VF_BOOL */
   'o','u','t','f','o','l','d','e','r','\0',
   /* 126. [1571]+5 PAGER, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'P','A','G','E','R','\0',
   /* 127. [1577]+4 PATH, a_AMV_VF_IMPORT|a_AMV_VF_NODEL|a_AMV_VF_ENV */
   'P','A','T','H','\0',
   /* 128. [1582]+4 page, a_AMV_VF_BOOL */
   'p','a','g','e','\0',
   /* 129. [1587]+8 password */
   'p','a','s','s','w','o','r','d','\0',
   /* 130. [1596]+7 piperaw, a_AMV_VF_BOOL */
   'p','i','p','e','r','a','w','\0',
   /* 131. [1604]+9 pop3-auth */
   'p','o','p','3','-','a','u','t','h','\0',
   /* 132. [1614]+14 pop3-bulk-load, a_AMV_VF_BOOL */
   'p','o','p','3','-','b','u','l','k','-','l','o','a','d','\0',
   /* 133. [1629]+14 pop3-keepalive */
   'p','o','p','3','-','k','e','e','p','a','l','i','v','e','\0',
   /* 134. [1644]+12 pop3-no-apop, a_AMV_VF_BOOL */
   'p','o','p','3','-','n','o','-','a','p','o','p','\0',
   /* 135. [1657]+17 pop3-use-starttls, a_AMV_VF_BOOL */
   'p','o','p','3','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 136. [1675]+18 print-alternatives, a_AMV_VF_BOOL */
   'p','r','i','n','t','-','a','l','t','e','r','n','a','t','i','v','e','s','\0',
   /* 137. [1694]+6 prompt, a_AMV_VF_I3VAL */
   'p','r','o','m','p','t','\0',
   /* 138. [1701]+5 quiet, a_AMV_VF_BOOL */
   'q','u','i','e','t','\0',
   /* 139. [1707]+5 quote */
   'q','u','o','t','e','\0',
   /* 140. [1713]+19 quote-as-attachment, a_AMV_VF_BOOL */
   'q','u','o','t','e','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 141. [1733]+10 quote-fold */
   'q','u','o','t','e','-','f','o','l','d','\0',
   /* 142. [1744]+16 recipients-in-cc, a_AMV_VF_BOOL */
   'r','e','c','i','p','i','e','n','t','s','-','i','n','-','c','c','\0',
   /* 143. [1761]+6 record */
   'r','e','c','o','r','d','\0',
   /* 144. [1768]+13 record-resent, a_AMV_VF_BOOL */
   'r','e','c','o','r','d','-','r','e','s','e','n','t','\0',
   /* 145. [1782]+21 reply-in-same-charset, a_AMV_VF_BOOL */
   'r','e','p','l','y','-','i','n','-','s','a','m','e','-','c','h','a','r','s','e','t','\0',
   /* 146. [1804]+13 reply-strings */
   'r','e','p','l','y','-','s','t','r','i','n','g','s','\0',
   /* 147. [1818]+7 replyto */
   'r','e','p','l','y','t','o','\0',
   /* 148. [1826]+15 reply-to-honour */
   'r','e','p','l','y','-','t','o','-','h','o','n','o','u','r','\0',
   /* 149. [1842]+17 rfc822-body-from_, a_AMV_VF_BOOL */
   'r','f','c','8','2','2','-','b','o','d','y','-','f','r','o','m','_','\0',
   /* 150. [1860]+5 SHELL, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'S','H','E','L','L','\0',
   /* 151. [1866]+5 SYSV3, a_AMV_VF_BOOL|a_AMV_VF_ENV */
   'S','Y','S','V','3','\0',
   /* 152. [1872]+4 save, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   's','a','v','e','\0',
   /* 153. [1877]+6 screen, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','c','r','e','e','n','\0',
   /* 154. [1884]+13 searchheaders, a_AMV_VF_BOOL */
   's','e','a','r','c','h','h','e','a','d','e','r','s','\0',
   /* 155. [1898]+12 sendcharsets */
   's','e','n','d','c','h','a','r','s','e','t','s','\0',
   /* 156. [1911]+28 sendcharsets-else-ttycharset, a_AMV_VF_BOOL */
   's','e','n','d','c','h','a','r','s','e','t','s','-','e','l','s','e','-','t','t','y','c','h','a','r','s','e','t','\0',
   /* 157. [1940]+6 sender */
   's','e','n','d','e','r','\0',
   /* 158. [1947]+8 sendmail */
   's','e','n','d','m','a','i','l','\0',
   /* 159. [1956]+18 sendmail-arguments */
   's','e','n','d','m','a','i','l','-','a','r','g','u','m','e','n','t','s','\0',
   /* 160. [1975]+29 sendmail-no-default-arguments, a_AMV_VF_BOOL */
   's','e','n','d','m','a','i','l','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 161. [2005]+17 sendmail-progname */
   's','e','n','d','m','a','i','l','-','p','r','o','g','n','a','m','e','\0',
   /* 162. [2023]+8 sendwait, a_AMV_VF_BOOL */
   's','e','n','d','w','a','i','t','\0',
   /* 163. [2032]+8 showlast, a_AMV_VF_BOOL */
   's','h','o','w','l','a','s','t','\0',
   /* 164. [2041]+8 showname, a_AMV_VF_BOOL */
   's','h','o','w','n','a','m','e','\0',
   /* 165. [2050]+6 showto, a_AMV_VF_BOOL */
   's','h','o','w','t','o','\0',
   /* 166. [2057]+4 Sign */
   'S','i','g','n','\0',
   /* 167. [2062]+4 sign */
   's','i','g','n','\0',
   /* 168. [2067]+9 signature */
   's','i','g','n','a','t','u','r','e','\0',
   /* 169. [2077]+13 skipemptybody, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   's','k','i','p','e','m','p','t','y','b','o','d','y','\0',
   /* 170. [2091]+12 smime-ca-dir */
   's','m','i','m','e','-','c','a','-','d','i','r','\0',
   /* 171. [2104]+13 smime-ca-file */
   's','m','i','m','e','-','c','a','-','f','i','l','e','\0',
   /* 172. [2118]+12 smime-cipher */
   's','m','i','m','e','-','c','i','p','h','e','r','\0',
   /* 173. [2131]+13 smime-crl-dir */
   's','m','i','m','e','-','c','r','l','-','d','i','r','\0',
   /* 174. [2145]+14 smime-crl-file */
   's','m','i','m','e','-','c','r','l','-','f','i','l','e','\0',
   /* 175. [2160]+22 smime-force-encryption, a_AMV_VF_BOOL */
   's','m','i','m','e','-','f','o','r','c','e','-','e','n','c','r','y','p','t','i','o','n','\0',
   /* 176. [2183]+19 smime-no-default-ca, a_AMV_VF_BOOL */
   's','m','i','m','e','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 177. [2203]+10 smime-sign, a_AMV_VF_BOOL */
   's','m','i','m','e','-','s','i','g','n','\0',
   /* 178. [2214]+15 smime-sign-cert */
   's','m','i','m','e','-','s','i','g','n','-','c','e','r','t','\0',
   /* 179. [2230]+24 smime-sign-include-certs */
   's','m','i','m','e','-','s','i','g','n','-','i','n','c','l','u','d','e','-','c','e','r','t','s','\0',
   /* 180. [2255]+25 smime-sign-message-digest */
   's','m','i','m','e','-','s','i','g','n','-','m','e','s','s','a','g','e','-','d','i','g','e','s','t','\0',
   /* 181. [2281]+4 smtp */
   's','m','t','p','\0',
   /* 182. [2286]+9 smtp-auth */
   's','m','t','p','-','a','u','t','h','\0',
   /* 183. [2296]+18 smtp-auth-password */
   's','m','t','p','-','a','u','t','h','-','p','a','s','s','w','o','r','d','\0',
   /* 184. [2315]+14 smtp-auth-user */
   's','m','t','p','-','a','u','t','h','-','u','s','e','r','\0',
   /* 185. [2330]+13 smtp-hostname */
   's','m','t','p','-','h','o','s','t','n','a','m','e','\0',
   /* 186. [2344]+17 smtp-use-starttls, a_AMV_VF_BOOL */
   's','m','t','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 187. [2362]+17 SOURCE_DATE_EPOCH, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV */
   'S','O','U','R','C','E','_','D','A','T','E','_','E','P','O','C','H','\0',
   /* 188. [2380]+14 spam-interface */
   's','p','a','m','-','i','n','t','e','r','f','a','c','e','\0',
   /* 189. [2395]+12 spam-maxsize, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','p','a','m','-','m','a','x','s','i','z','e','\0',
   /* 190. [2408]+13 spamc-command */
   's','p','a','m','c','-','c','o','m','m','a','n','d','\0',
   /* 191. [2422]+15 spamc-arguments */
   's','p','a','m','c','-','a','r','g','u','m','e','n','t','s','\0',
   /* 192. [2438]+10 spamc-user */
   's','p','a','m','c','-','u','s','e','r','\0',
   /* 193. [2449]+12 spamd-socket */
   's','p','a','m','d','-','s','o','c','k','e','t','\0',
   /* 194. [2462]+10 spamd-user */
   's','p','a','m','d','-','u','s','e','r','\0',
   /* 195. [2473]+14 spamfilter-ham */
   's','p','a','m','f','i','l','t','e','r','-','h','a','m','\0',
   /* 196. [2488]+16 spamfilter-noham */
   's','p','a','m','f','i','l','t','e','r','-','n','o','h','a','m','\0',
   /* 197. [2505]+17 spamfilter-nospam */
   's','p','a','m','f','i','l','t','e','r','-','n','o','s','p','a','m','\0',
   /* 198. [2523]+15 spamfilter-rate */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','\0',
   /* 199. [2539]+25 spamfilter-rate-scanscore */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','-','s','c','a','n','s','c','o','r','e','\0',
   /* 200. [2565]+15 spamfilter-spam */
   's','p','a','m','f','i','l','t','e','r','-','s','p','a','m','\0',
   /* 201. [2581]+10 ssl-ca-dir */
   's','s','l','-','c','a','-','d','i','r','\0',
   /* 202. [2592]+11 ssl-ca-file */
   's','s','l','-','c','a','-','f','i','l','e','\0',
   /* 203. [2604]+8 ssl-cert */
   's','s','l','-','c','e','r','t','\0',
   /* 204. [2613]+15 ssl-cipher-list */
   's','s','l','-','c','i','p','h','e','r','-','l','i','s','t','\0',
   /* 205. [2629]+15 ssl-config-file */
   's','s','l','-','c','o','n','f','i','g','-','f','i','l','e','\0',
   /* 206. [2645]+11 ssl-crl-dir */
   's','s','l','-','c','r','l','-','d','i','r','\0',
   /* 207. [2657]+12 ssl-crl-file */
   's','s','l','-','c','r','l','-','f','i','l','e','\0',
   /* 208. [2670]+7 ssl-key */
   's','s','l','-','k','e','y','\0',
   /* 209. [2678]+10 ssl-method */
   's','s','l','-','m','e','t','h','o','d','\0',
   /* 210. [2689]+17 ssl-no-default-ca, a_AMV_VF_BOOL */
   's','s','l','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 211. [2707]+12 ssl-protocol */
   's','s','l','-','p','r','o','t','o','c','o','l','\0',
   /* 212. [2720]+12 ssl-rand-egd */
   's','s','l','-','r','a','n','d','-','e','g','d','\0',
   /* 213. [2733]+13 ssl-rand-file */
   's','s','l','-','r','a','n','d','-','f','i','l','e','\0',
   /* 214. [2747]+10 ssl-verify */
   's','s','l','-','v','e','r','i','f','y','\0',
   /* 215. [2758]+10 stealthmua */
   's','t','e','a','l','t','h','m','u','a','\0',
   /* 216. [2769]+4 TERM, a_AMV_VF_ENV */
   'T','E','R','M','\0',
   /* 217. [2774]+6 TMPDIR, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'T','M','P','D','I','R','\0',
   /* 218. [2781]+7 termcap */
   't','e','r','m','c','a','p','\0',
   /* 219. [2789]+15 termcap-disable, a_AMV_VF_BOOL */
   't','e','r','m','c','a','p','-','d','i','s','a','b','l','e','\0',
   /* 220. [2805]+8 toplines, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM */
   't','o','p','l','i','n','e','s','\0',
   /* 221. [2814]+10 topsqueeze, a_AMV_VF_BOOL */
   't','o','p','s','q','u','e','e','z','e','\0',
   /* 222. [2825]+10 ttycharset */
   't','t','y','c','h','a','r','s','e','t','\0',
   /* 223. [2836]+4 USER, a_AMV_VF_IMPORT|a_AMV_VF_RDONLY|a_AMV_VF_ENV */
   'U','S','E','R','\0',
   /* 224. [2841]+5 umask, a_AMV_VF_I3VAL|a_AMV_VF_NODEL|a_AMV_VF_POSNUM|a_AMV_VF_VIP */
   'u','m','a','s','k','\0',
   /* 225. [2847]+4 user */
   'u','s','e','r','\0',
   /* 226. [2852]+6 VISUAL, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV */
   'V','I','S','U','A','L','\0',
   /* 227. [2859]+10 v15-compat, a_AMV_VF_BOOL */
   'v','1','5','-','c','o','m','p','a','t','\0',
   /* 228. [2870]+7 verbose, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'v','e','r','b','o','s','e','\0',
   /* 229. [2878]+7 version, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','\0',
   /* 230. [2886]+13 version-major, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','-','m','a','j','o','r','\0',
   /* 231. [2900]+13 version-minor, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','-','m','i','n','o','r','\0',
   /* 232. [2914]+14 version-update, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','-','u','p','d','a','t','e','\0',
   /* 233. [2929]+15 writebackedited, a_AMV_VF_BOOL */
   'w','r','i','t','e','b','a','c','k','e','d','i','t','e','d','\0',
};

n_CTA(a_AMV_VF_NONE == 0, "Value not 0 as expected");
static struct a_amv_var_map const a_amv_var_map[] = {
   {3372302411u, 0u, a_AMV_VF_NONE},   /* on_compose_enter */
   {3380260282u, 17u, a_AMV_VF_NONE},   /* on_compose_leave */
   {1681309687u, 34u, a_AMV_VF_NONE},   /* compose_from */
   {1783481892u, 47u, a_AMV_VF_NONE},   /* compose_sender */
   {1658005574u, 62u, a_AMV_VF_NONE},   /* compose_to */
   {1658005001u, 73u, a_AMV_VF_NONE},   /* compose_cc */
   {3174556491u, 84u, a_AMV_VF_NONE},   /* compose_bcc */
   {3632478067u, 96u, a_AMV_VF_NONE},   /* compose_subject */
   {3722159545u, 112u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* add_file_recipients */
   {838023451u, 132u, a_AMV_VF_NONE},   /* agent_shell_lookup */
   {3928217024u, 151u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* allnet */
   {3933094936u, 158u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* append */
   {109535u, 165u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ask */
   {437227595u, 169u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askatend */
   {1544133716u, 178u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askattach */
   {3936469383u, 188u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askbcc */
   {119286981u, 195u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askcc */
   {1055088464u, 201u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* asksign */
   {3936488489u, 209u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* asksub */
   {1653823630u, 216u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* attachment_ask_content_description */
   {2717622527u, 251u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* attachment_ask_content_disposition */
   {1759766423u, 286u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* attachment_ask_content_id */
   {830642604u, 312u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* attachment_ask_content_type */
   {2100791799u, 340u, a_AMV_VF_NONE},   /* attrlist */
   {1143881025u, 349u, a_AMV_VF_NONE},   /* autobcc */
   {3939178815u, 357u, a_AMV_VF_NONE},   /* autocc */
   {2551200844u, 364u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autocollapse */
   {163072614u, 377u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autoprint */
   {1231424433u, 387u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autothread */
   {3388960065u, 398u, a_AMV_VF_NONE},   /* autosort */
   {3631192u, 407u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bang */
   {625280330u, 412u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* batch_exit_on_error */
   {321383761u, 432u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* bind_timeout */
   {170960u, 445u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdannounce */
   {3120210877u, 457u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdcompat */
   {4132654694u, 467u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdflags */
   {2716084787u, 476u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdheadline */
   {2338050259u, 488u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdmsgs */
   {4143546805u, 496u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdorder */
   {3813975201u, 505u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV},   /* COLUMNS */
   {358823789u, 513u, a_AMV_VF_NONE},   /* charset_7bit */
   {358859726u, 526u, a_AMV_VF_NONE},   /* charset_8bit */
   {3269304427u, 539u, a_AMV_VF_NONE},   /* charset_unknown_8bit */
   {111508u, 560u, a_AMV_VF_NONE},   /* cmd */
   {482327989u, 564u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* colour_disable */
   {2857965296u, 579u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* colour_pager */
   {111689u, 592u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* crt */
   {2974539481u, 596u, a_AMV_VF_NONE|a_AMV_VF_NOCNTRLS},   /* customhdr */
   {2521070u, 606u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* DEAD */
   {3657134018u, 611u, a_AMV_VF_NONE},   /* datefield */
   {2384089013u, 621u, a_AMV_VF_NONE},   /* datefield_markout_older */
   {122332423u, 645u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* debug */
   {1691626112u, 651u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* disposition_notification_send */
   {112679u, 681u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dot */
   {1781498776u, 685u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dotlock_ignore_error */
   {2783702311u, 706u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* EDITOR */
   {3877730807u, 713u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* editalong */
   {1055429730u, 723u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* editheaders */
   {171820376u, 735u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* emptybox */
   {2449114909u, 744u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* emptystart */
   {947851527u, 755u, a_AMV_VF_NONE},   /* encoding */
   {4092722801u, 764u, a_AMV_VF_NONE},   /* escape */
   {3254669595u, 771u, a_AMV_VF_NONE},   /* expandaddr */
   {3254684944u, 782u, a_AMV_VF_NONE},   /* expandargv */
   {1806590975u, 793u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* features */
   {124963293u, 802u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* flipr */
   {4127440860u, 808u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* folder */
   {207142394u, 815u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* _folder_resolved */
   {3184215642u, 832u, a_AMV_VF_NONE},   /* folder_hook */
   {845432648u, 844u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* followup_to */
   {1360940784u, 856u, a_AMV_VF_NONE},   /* followup_to_honour */
   {2102400300u, 875u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* forward_as_attachment */
   {3793492u, 897u, a_AMV_VF_NONE},   /* from */
   {3777473511u, 902u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* fullnames */
   {1142629489u, 912u, a_AMV_VF_NONE},   /* fwdheading */
   {2676105u, 923u, a_AMV_VF_NONE|a_AMV_VF_IMPORT|a_AMV_VF_NODEL|a_AMV_VF_VIP|a_AMV_VF_ENV},   /* HOME */
   {4193457129u, 928u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL|a_AMV_VF_VIP},   /* header */
   {1124823322u, 935u, a_AMV_VF_NONE},   /* headline */
   {3102083359u, 944u, a_AMV_VF_NONE},   /* headline_bidi */
   {78202687u, 958u, a_AMV_VF_NONE},   /* history_file */
   {2581576228u, 971u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* history_gabby */
   {4251937947u, 985u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* history_gabby_persist */
   {78670330u, 1007u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM},   /* history_size */
   {3861991u, 1020u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* hold */
   {1878076063u, 1025u, a_AMV_VF_NONE},   /* hostname */
   {2723216029u, 1034u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* idna_disable */
   {4235443940u, 1047u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignore */
   {4097949886u, 1054u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignoreeof */
   {1578583856u, 1064u, a_AMV_VF_NONE},   /* indentprefix */
   {3958693u, 1077u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep */
   {3727474588u, 1082u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep_content_length */
   {302149108u, 1102u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keepsave */
   {92840699u, 1111u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV},   /* LINES */
   {3063938707u, 1117u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* LISTER */
   {2546090755u, 1124u, a_AMV_VF_NONE|a_AMV_VF_IMPORT|a_AMV_VF_RDONLY|a_AMV_VF_ENV},   /* LOGNAME */
   {4215099357u, 1132u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line_editor_disable */
   {141716907u, 1152u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line_editor_no_defaults */
   {2840419u, 1176u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* MAIL */
   {3093219064u, 1181u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* MAILRC */
   {2841718u, 1188u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* MBOX */
   {2312309028u, 1193u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* markanswered */
   {4233006470u, 1206u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* memdebug */
   {130334368u, 1215u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* message_id_disable */
   {125627982u, 1234u, a_AMV_VF_NONE},   /* message_inject_head */
   {126055142u, 1254u, a_AMV_VF_NONE},   /* message_inject_tail */
   {133025124u, 1274u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* metoo */
   {3414355303u, 1280u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime_allow_text_controls */
   {3908858503u, 1305u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime_alternative_favour_rich */
   {3192709189u, 1334u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* mime_counter_evidence */
   {1028657528u, 1356u, a_AMV_VF_NONE},   /* mimetypes_load_control */
   {122626u, 1379u, a_AMV_VF_NONE},   /* mta */
   {2713248165u, 1383u, a_AMV_VF_NONE},   /* mta_arguments */
   {4035420705u, 1397u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta_no_default_arguments */
   {1102401135u, 1422u, a_AMV_VF_NONE},   /* mta_argv0 */
   {4280681563u, 1432u, a_AMV_VF_NONE},   /* NAIL_EXTRA_RC */
   {1593687682u, 1446u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* NAIL_NO_SYSTEM_RC */
   {639934357u, 1464u, a_AMV_VF_NONE},   /* NAIL_HEAD */
   {1058233243u, 1474u, a_AMV_VF_NONE},   /* NAIL_HISTFILE */
   {1058700886u, 1488u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM},   /* NAIL_HISTSIZE */
   {640361517u, 1502u, a_AMV_VF_NONE},   /* NAIL_TAIL */
   {95075740u, 1512u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* NETRC */
   {1137717571u, 1518u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* netrc_lookup */
   {4047680087u, 1531u, a_AMV_VF_NONE},   /* netrc_pipe */
   {985178617u, 1542u, a_AMV_VF_NONE},   /* newfolders */
   {130414157u, 1553u, a_AMV_VF_NONE},   /* newmail */
   {1400017300u, 1561u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* outfolder */
   {97289263u, 1571u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* PAGER */
   {2948589u, 1577u, a_AMV_VF_NONE|a_AMV_VF_IMPORT|a_AMV_VF_NODEL|a_AMV_VF_ENV},   /* PATH */
   {4134077u, 1582u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* page */
   {2621674035u, 1587u, a_AMV_VF_NONE},   /* password */
   {2861320984u, 1596u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* piperaw */
   {2396252929u, 1604u, a_AMV_VF_NONE},   /* pop3_auth */
   {275342634u, 1614u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* pop3_bulk_load */
   {1495995749u, 1629u, a_AMV_VF_NONE},   /* pop3_keepalive */
   {3632267817u, 1644u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* pop3_no_apop */
   {43237290u, 1657u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* pop3_use_starttls */
   {1388395788u, 1675u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* print_alternatives */
   {227503234u, 1694u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* prompt */
   {138331496u, 1701u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quiet */
   {138338510u, 1707u, a_AMV_VF_NONE},   /* quote */
   {3820786885u, 1713u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quote_as_attachment */
   {1182381408u, 1733u, a_AMV_VF_NONE},   /* quote_fold */
   {682388781u, 1744u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* recipients_in_cc */
   {289928031u, 1761u, a_AMV_VF_NONE},   /* record */
   {3191066333u, 1768u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* record_resent */
   {3710195994u, 1782u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* reply_in_same_charset */
   {4144529571u, 1804u, a_AMV_VF_NONE},   /* reply_strings */
   {993007855u, 1818u, a_AMV_VF_NONE},   /* replyto */
   {4037862148u, 1826u, a_AMV_VF_NONE},   /* reply_to_honour */
   {145783858u, 1842u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* rfc822_body_from_ */
   {101096632u, 1860u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* SHELL */
   {101723112u, 1866u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_ENV},   /* SYSV3 */
   {4242383u, 1872u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* save */
   {327219328u, 1877u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* screen */
   {2344495826u, 1884u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* searchheaders */
   {1707020871u, 1898u, a_AMV_VF_NONE},   /* sendcharsets */
   {259282709u, 1911u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* sendcharsets_else_ttycharset */
   {329446337u, 1940u, a_AMV_VF_NONE},   /* sender */
   {2285047981u, 1947u, a_AMV_VF_NONE},   /* sendmail */
   {2932368656u, 1956u, a_AMV_VF_NONE},   /* sendmail_arguments */
   {1421298860u, 1975u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* sendmail_no_default_arguments */
   {4267157331u, 2005u, a_AMV_VF_NONE},   /* sendmail_progname */
   {2285407359u, 2023u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* sendwait */
   {1926116885u, 2032u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showlast */
   {1926188546u, 2041u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showname */
   {333061220u, 2050u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showto */
   {3100625u, 2057u, a_AMV_VF_NONE},   /* Sign */
   {4250609u, 2062u, a_AMV_VF_NONE},   /* sign */
   {994697266u, 2067u, a_AMV_VF_NONE},   /* signature */
   {3875901652u, 2077u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* skipemptybody */
   {3002585464u, 2091u, a_AMV_VF_NONE},   /* smime_ca_dir */
   {301144281u, 2104u, a_AMV_VF_NONE},   /* smime_ca_file */
   {3014484835u, 2118u, a_AMV_VF_NONE},   /* smime_cipher */
   {1039105045u, 2131u, a_AMV_VF_NONE},   /* smime_crl_dir */
   {4225767190u, 2145u, a_AMV_VF_NONE},   /* smime_crl_file */
   {3116904399u, 2160u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime_force_encryption */
   {3384448360u, 2183u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime_no_default_ca */
   {105885657u, 2203u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime_sign */
   {2215302260u, 2214u, a_AMV_VF_NONE},   /* smime_sign_cert */
   {1036659416u, 2230u, a_AMV_VF_NONE},   /* smime_sign_include_certs */
   {3719373112u, 2255u, a_AMV_VF_NONE},   /* smime_sign_message_digest */
   {4255396u, 2281u, a_AMV_VF_NONE},   /* smtp */
   {3589879203u, 2286u, a_AMV_VF_NONE},   /* smtp_auth */
   {1996663907u, 2296u, a_AMV_VF_NONE},   /* smtp_auth_password */
   {2594939183u, 2315u, a_AMV_VF_NONE},   /* smtp_auth_user */
   {2613227248u, 2330u, a_AMV_VF_NONE},   /* smtp_hostname */
   {1310886988u, 2344u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smtp_use_starttls */
   {3578734108u, 2362u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_ENV},   /* SOURCE_DATE_EPOCH */
   {2190606319u, 2380u, a_AMV_VF_NONE},   /* spam_interface */
   {2952684415u, 2395u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* spam_maxsize */
   {3055596256u, 2408u, a_AMV_VF_NONE},   /* spamc_command */
   {3800420503u, 2422u, a_AMV_VF_NONE},   /* spamc_arguments */
   {4245507488u, 2438u, a_AMV_VF_NONE},   /* spamc_user */
   {1558523435u, 2449u, a_AMV_VF_NONE},   /* spamd_socket */
   {4284642881u, 2462u, a_AMV_VF_NONE},   /* spamd_user */
   {2420736634u, 2473u, a_AMV_VF_NONE},   /* spamfilter_ham */
   {3374858487u, 2488u, a_AMV_VF_NONE},   /* spamfilter_noham */
   {3996559026u, 2505u, a_AMV_VF_NONE},   /* spamfilter_nospam */
   {2575257296u, 2523u, a_AMV_VF_NONE},   /* spamfilter_rate */
   {4190460190u, 2539u, a_AMV_VF_NONE},   /* spamfilter_rate_scanscore */
   {2575308949u, 2565u, a_AMV_VF_NONE},   /* spamfilter_spam */
   {1179440559u, 2581u, a_AMV_VF_NONE},   /* ssl_ca_dir */
   {266904560u, 2592u, a_AMV_VF_NONE},   /* ssl_ca_file */
   {3041879213u, 2604u, a_AMV_VF_NONE},   /* ssl_cert */
   {2789248355u, 2613u, a_AMV_VF_NONE},   /* ssl_cipher_list */
   {390091074u, 2629u, a_AMV_VF_NONE},   /* ssl_config_file */
   {1004865324u, 2645u, a_AMV_VF_NONE},   /* ssl_crl_dir */
   {3095856397u, 2657u, a_AMV_VF_NONE},   /* ssl_crl_file */
   {2825347880u, 2670u, a_AMV_VF_NONE},   /* ssl_key */
   {1578094240u, 2678u, a_AMV_VF_NONE},   /* ssl_method */
   {1961350591u, 2689u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ssl_no_default_ca */
   {3286757489u, 2707u, a_AMV_VF_NONE},   /* ssl_protocol */
   {2083698465u, 2720u, a_AMV_VF_NONE},   /* ssl_rand_egd */
   {42611089u, 2733u, a_AMV_VF_NONE},   /* ssl_rand_file */
   {1930241716u, 2747u, a_AMV_VF_NONE},   /* ssl_verify */
   {4266102040u, 2758u, a_AMV_VF_NONE},   /* stealthmua */
   {3096632u, 2769u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* TERM */
   {3381640432u, 2774u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* TMPDIR */
   {3578326988u, 2781u, a_AMV_VF_NONE},   /* termcap */
   {881438381u, 2789u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* termcap_disable */
   {2071224238u, 2805u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM},   /* toplines */
   {1477079445u, 2814u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* topsqueeze */
   {113531019u, 2825u, a_AMV_VF_NONE},   /* ttycharset */
   {3147391u, 2836u, a_AMV_VF_NONE|a_AMV_VF_IMPORT|a_AMV_VF_RDONLY|a_AMV_VF_ENV},   /* USER */
   {142779425u, 2841u, a_AMV_VF_NONE|a_AMV_VF_I3VAL|a_AMV_VF_NODEL|a_AMV_VF_POSNUM|a_AMV_VF_VIP},   /* umask */
   {4333311u, 2847u, a_AMV_VF_NONE},   /* user */
   {3455293588u, 2852u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_ENV},   /* VISUAL */
   {2303937485u, 2859u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* v15_compat */
   {1865913974u, 2870u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* verbose */
   {1866518246u, 2878u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version */
   {3587799308u, 2886u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version_major */
   {3588091160u, 2900u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version_minor */
   {2763901430u, 2914u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version_update */
   {3469190955u, 2929u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* writebackedited */
};

#ifndef __CREATE_OKEY_MAP_PL
# ifdef HAVE_PUTENV
#  define a_X(X) X
# else
#  define a_X(X)
# endif

/* Unfortunately init of varsized buffer won't work: define "subclass"es */
static char const a_amv_var_virt_features_val[] = {VAL_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   ui16_t av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_features = {NULL, a_amv_var_virt_features_val, a_X(0 COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "features"};

static char const a_amv_var_virt_version_val[] = {VERSION};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   ui16_t av_flags;
   char const av_name[7 +1];
} const a_amv_var_virt_version = {NULL, a_amv_var_virt_version_val, a_X(0 COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version"};

static char const a_amv_var_virt_version_major_val[] = {VERSION_MAJOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   ui16_t av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_major = {NULL, a_amv_var_virt_version_major_val, a_X(0 COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version-major"};

static char const a_amv_var_virt_version_minor_val[] = {VERSION_MINOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   ui16_t av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_minor = {NULL, a_amv_var_virt_version_minor_val, a_X(0 COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version-minor"};

static char const a_amv_var_virt_version_update_val[] = {VERSION_UPDATE};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   ui16_t av_flags;
   char const av_name[14 +1];
} const a_amv_var_virt_version_update = {NULL, a_amv_var_virt_version_update_val, a_X(0 COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version-update"};

# undef a_X

#define a_AMV_VAR_VIRTS_CNT 5
static struct a_amv_var_virt const a_amv_var_virts[] = {
   {ok_v_features, {0,}, (void const*)&a_amv_var_virt_features},
   {ok_v_version, {0,}, (void const*)&a_amv_var_virt_version},
   {ok_v_version_major, {0,}, (void const*)&a_amv_var_virt_version_major},
   {ok_v_version_minor, {0,}, (void const*)&a_amv_var_virt_version_minor},
   {ok_v_version_update, {0,}, (void const*)&a_amv_var_virt_version_update},
};

#define a_AMV_VAR_I3VALS_CNT 5
static struct a_amv_var_defval const a_amv_var_i3vals[] = {
   {ok_b_asksub, {0,}, NULL},
   {ok_b_header, {0,}, NULL},
   {ok_v_prompt, {0,}, "\\& "},
   {ok_b_save, {0,}, NULL},
   {ok_v_umask, {0,}, "0077"},
};

#define a_AMV_VAR_DEFVALS_CNT 11
static struct a_amv_var_defval const a_amv_var_defvals[] = {
   {ok_v_DEAD, {0,}, VAL_DEAD},
   {ok_v_EDITOR, {0,}, VAL_EDITOR},
   {ok_v_LISTER, {0,}, VAL_LISTER},
   {ok_v_MAILRC, {0,}, VAL_MAILRC},
   {ok_v_MBOX, {0,}, VAL_MBOX},
   {ok_v_NETRC, {0,}, VAL_NETRC},
   {ok_v_PAGER, {0,}, VAL_PAGER},
   {ok_v_SHELL, {0,}, VAL_SHELL},
   {ok_v_TMPDIR, {0,}, VAL_TMPDIR},
   {ok_v_VISUAL, {0,}, VAL_VISUAL},
   {ok_v_toplines, {0,}, "5"},
};
#endif /* __CREATE_OKEY_MAP_PL */

#define a_AMV_VAR_REV_ILL 234u
#define a_AMV_VAR_REV_PRIME 419u
#define a_AMV_VAR_REV_LONGEST 5u
#define a_AMV_VAR_REV_WRAPAROUND 1
static ui8_t const a_amv_var_revmap[a_AMV_VAR_REV_PRIME] = {
  95u, 34u, 68u, 108u, 194u, 234u, 234u, 69u, 33u, 152u,
  233u, 234u, 3u, 197u, 225u, 234u, 234u, 145u, 97u, 234u,
  234u, 153u, 234u, 54u, 234u, 166u, 234u, 234u, 234u, 234u,
  125u, 120u, 181u, 200u, 226u, 234u, 222u, 234u, 86u, 170u,
  234u, 234u, 234u, 19u, 144u, 157u, 119u, 39u, 140u, 192u,
  103u, 213u, 234u, 41u, 43u, 234u, 158u, 234u, 6u, 214u,
  99u, 137u, 147u, 156u, 234u, 168u, 234u, 234u, 83u, 234u,
  234u, 234u, 234u, 234u, 66u, 29u, 234u, 234u, 38u, 234u,
  234u, 234u, 234u, 234u, 234u, 234u, 127u, 185u, 234u, 159u,
  234u, 37u, 234u, 174u, 234u, 234u, 234u, 234u, 234u, 78u,
  88u, 234u, 234u, 234u, 234u, 234u, 234u, 67u, 79u, 234u,
  81u, 85u, 234u, 234u, 221u, 184u, 234u, 234u, 234u, 2u,
  234u, 234u, 234u, 234u, 234u, 100u, 234u, 234u, 199u, 173u,
  228u, 24u, 204u, 234u, 234u, 234u, 132u, 234u, 30u, 14u,
  117u, 122u, 106u, 143u, 193u, 234u, 234u, 82u, 74u, 224u,
  40u, 234u, 130u, 212u, 234u, 57u, 188u, 161u, 234u, 234u,
  234u, 160u, 176u, 231u, 234u, 234u, 105u, 121u, 98u, 177u,
  195u, 234u, 234u, 234u, 234u, 234u, 12u, 11u, 25u, 118u,
  234u, 154u, 171u, 234u, 234u, 0u, 234u, 234u, 234u, 234u,
  234u, 234u, 234u, 28u, 56u, 16u, 232u, 180u, 234u, 234u,
  234u, 49u, 60u, 179u, 227u, 229u, 155u, 234u, 58u, 63u,
  148u, 190u, 234u, 5u, 96u, 139u, 165u, 189u, 234u, 187u,
  234u, 234u, 216u, 128u, 77u, 234u, 234u, 234u, 102u, 172u,
  234u, 234u, 115u, 219u, 234u, 45u, 46u, 178u, 186u, 234u,
  47u, 234u, 234u, 234u, 22u, 133u, 234u, 91u, 234u, 18u,
  36u, 104u, 206u, 129u, 234u, 234u, 234u, 13u, 111u, 20u,
  123u, 135u, 234u, 10u, 234u, 234u, 116u, 234u, 234u, 234u,
  234u, 175u, 234u, 167u, 183u, 234u, 234u, 234u, 110u, 210u,
  8u, 112u, 141u, 163u, 223u, 72u, 32u, 234u, 234u, 146u,
  234u, 35u, 70u, 208u, 164u, 209u, 234u, 234u, 234u, 234u,
  234u, 234u, 234u, 202u, 234u, 7u, 234u, 234u, 90u, 131u,
  101u, 234u, 150u, 234u, 65u, 207u, 234u, 234u, 234u, 234u,
  234u, 136u, 138u, 234u, 84u, 234u, 114u, 80u, 27u, 44u,
  215u, 234u, 234u, 182u, 198u, 234u, 234u, 234u, 234u, 234u,
  234u, 71u, 234u, 234u, 234u, 31u, 51u, 52u, 26u, 234u,
  149u, 162u, 234u, 142u, 230u, 61u, 92u, 234u, 234u, 234u,
  234u, 196u, 21u, 42u, 62u, 234u, 48u, 4u, 218u, 93u,
  234u, 75u, 217u, 234u, 17u, 234u, 234u, 109u, 234u, 76u,
  73u, 23u, 50u, 94u, 107u, 234u, 234u, 53u, 151u, 203u,
  234u, 55u, 201u, 134u, 169u, 220u, 126u, 234u, 205u, 211u,
  89u, 234u, 234u, 113u, 234u, 234u, 9u, 64u, 1u, 124u,
  234u, 59u, 234u, 234u, 234u, 87u, 234u, 15u, 191u
};
