/*@ okeys.h, generated by ./create-okey-map.pl on Mon Jan  6 18:52:07 2014.
 *@ See acmava.c for more */

static char const _var_keydat[] = {
   /* 0. [0]+19 add-file-recipients, binary=1 */
   'a','d','d','-','f','i','l','e','-','r','e','c','i','p','i','e','n','t','s','\0',
   /* 1. [20]+6 allnet, binary=1 */
   'a','l','l','n','e','t','\0',
   /* 2. [27]+6 append, binary=1 */
   'a','p','p','e','n','d','\0',
   /* 3. [34]+3 ask, binary=1 */
   'a','s','k','\0',
   /* 4. [38]+8 askatend, binary=1 */
   'a','s','k','a','t','e','n','d','\0',
   /* 5. [47]+9 askattach, binary=1 */
   'a','s','k','a','t','t','a','c','h','\0',
   /* 6. [57]+6 askbcc, binary=1 */
   'a','s','k','b','c','c','\0',
   /* 7. [64]+5 askcc, binary=1 */
   'a','s','k','c','c','\0',
   /* 8. [70]+7 asksign, binary=1 */
   'a','s','k','s','i','g','n','\0',
   /* 9. [78]+6 asksub, binary=1 */
   'a','s','k','s','u','b','\0',
   /* 10. [85]+34 attachment-ask-content-description, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','\0',
   /* 11. [120]+34 attachment-ask-content-disposition, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','i','s','p','o','s','i','t','i','o','n','\0',
   /* 12. [155]+25 attachment-ask-content-id, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','i','d','\0',
   /* 13. [181]+27 attachment-ask-content-type, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','t','y','p','e','\0',
   /* 14. [209]+12 autocollapse, binary=1 */
   'a','u','t','o','c','o','l','l','a','p','s','e','\0',
   /* 15. [222]+9 autoprint, binary=1 */
   'a','u','t','o','p','r','i','n','t','\0',
   /* 16. [232]+10 autothread, binary=1 */
   'a','u','t','o','t','h','r','e','a','d','\0',
   /* 17. [243]+4 bang, binary=1 */
   'b','a','n','g','\0',
   /* 18. [248]+19 batch-exit-on-error, binary=1 */
   'b','a','t','c','h','-','e','x','i','t','-','o','n','-','e','r','r','o','r','\0',
   /* 19. [268]+11 bsdannounce, binary=1 */
   'b','s','d','a','n','n','o','u','n','c','e','\0',
   /* 20. [280]+9 bsdcompat, binary=1 */
   'b','s','d','c','o','m','p','a','t','\0',
   /* 21. [290]+8 bsdflags, binary=1 */
   'b','s','d','f','l','a','g','s','\0',
   /* 22. [299]+11 bsdheadline, binary=1 */
   'b','s','d','h','e','a','d','l','i','n','e','\0',
   /* 23. [311]+7 bsdmsgs, binary=1 */
   'b','s','d','m','s','g','s','\0',
   /* 24. [319]+8 bsdorder, binary=1 */
   'b','s','d','o','r','d','e','r','\0',
   /* 25. [328]+6 bsdset, binary=1 */
   'b','s','d','s','e','t','\0',
   /* 26. [335]+14 colour-disable, binary=1 */
   'c','o','l','o','u','r','-','d','i','s','a','b','l','e','\0',
   /* 27. [350]+5 debug, binary=1 */
   'd','e','b','u','g','\0',
   /* 28. [356]+12 disconnected, binary=1 */
   'd','i','s','c','o','n','n','e','c','t','e','d','\0',
   /* 29. [369]+3 dot, binary=1 */
   'd','o','t','\0',
   /* 30. [373]+9 editalong, binary=1 */
   'e','d','i','t','a','l','o','n','g','\0',
   /* 31. [383]+11 editheaders, binary=1 */
   'e','d','i','t','h','e','a','d','e','r','s','\0',
   /* 32. [395]+8 emptybox, binary=1 */
   'e','m','p','t','y','b','o','x','\0',
   /* 33. [404]+10 emptystart, binary=1 */
   'e','m','p','t','y','s','t','a','r','t','\0',
   /* 34. [415]+5 flipr, binary=1 */
   'f','l','i','p','r','\0',
   /* 35. [421]+21 forward-as-attachment, binary=1 */
   'f','o','r','w','a','r','d','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 36. [443]+9 fullnames, binary=1 */
   'f','u','l','l','n','a','m','e','s','\0',
   /* 37. [453]+6 header, binary=1 */
   'h','e','a','d','e','r','\0',
   /* 38. [460]+4 hold, binary=1 */
   'h','o','l','d','\0',
   /* 39. [465]+12 idna-disable, binary=1 */
   'i','d','n','a','-','d','i','s','a','b','l','e','\0',
   /* 40. [478]+6 ignore, binary=1 */
   'i','g','n','o','r','e','\0',
   /* 41. [485]+9 ignoreeof, binary=1 */
   'i','g','n','o','r','e','e','o','f','\0',
   /* 42. [495]+17 imap-use-starttls, binary=1 */
   'i','m','a','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 43. [513]+4 keep, binary=1 */
   'k','e','e','p','\0',
   /* 44. [518]+19 keep-content-length, binary=1 */
   'k','e','e','p','-','c','o','n','t','e','n','t','-','l','e','n','g','t','h','\0',
   /* 45. [538]+8 keepsave, binary=1 */
   'k','e','e','p','s','a','v','e','\0',
   /* 46. [547]+19 line-editor-disable, binary=1 */
   'l','i','n','e','-','e','d','i','t','o','r','-','d','i','s','a','b','l','e','\0',
   /* 47. [567]+12 markanswered, binary=1 */
   'm','a','r','k','a','n','s','w','e','r','e','d','\0',
   /* 48. [580]+18 message-id-disable, binary=1 */
   'm','e','s','s','a','g','e','-','i','d','-','d','i','s','a','b','l','e','\0',
   /* 49. [599]+5 metoo, binary=1 */
   'm','e','t','o','o','\0',
   /* 50. [605]+24 mime-allow-text-controls, binary=1 */
   'm','i','m','e','-','a','l','l','o','w','-','t','e','x','t','-','c','o','n','t','r','o','l','s','\0',
   /* 51. [630]+21 mime-counter-evidence, binary=1 */
   'm','i','m','e','-','c','o','u','n','t','e','r','-','e','v','i','d','e','n','c','e','\0',
   /* 52. [652]+9 outfolder, binary=1 */
   'o','u','t','f','o','l','d','e','r','\0',
   /* 53. [662]+4 page, binary=1 */
   'p','a','g','e','\0',
   /* 54. [667]+7 piperaw, binary=1 */
   'p','i','p','e','r','a','w','\0',
   /* 55. [675]+14 pop3-bulk-load, binary=1 */
   'p','o','p','3','-','b','u','l','k','-','l','o','a','d','\0',
   /* 56. [690]+12 pop3-no-apop, binary=1 */
   'p','o','p','3','-','n','o','-','a','p','o','p','\0',
   /* 57. [703]+17 pop3-use-starttls, binary=1 */
   'p','o','p','3','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 58. [721]+15 print-all-chars, binary=1 */
   'p','r','i','n','t','-','a','l','l','-','c','h','a','r','s','\0',
   /* 59. [737]+18 print-alternatives, binary=1 */
   'p','r','i','n','t','-','a','l','t','e','r','n','a','t','i','v','e','s','\0',
   /* 60. [756]+5 quiet, binary=1 */
   'q','u','i','e','t','\0',
   /* 61. [762]+19 quote-as-attachment, binary=1 */
   'q','u','o','t','e','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 62. [782]+16 recipients-in-cc, binary=1 */
   'r','e','c','i','p','i','e','n','t','s','-','i','n','-','c','c','\0',
   /* 63. [799]+13 record-resent, binary=1 */
   'r','e','c','o','r','d','-','r','e','s','e','n','t','\0',
   /* 64. [813]+21 reply-in-same-charset, binary=1 */
   'r','e','p','l','y','-','i','n','-','s','a','m','e','-','c','h','a','r','s','e','t','\0',
   /* 65. [835]+8 Replyall, binary=1 */
   'R','e','p','l','y','a','l','l','\0',
   /* 66. [844]+17 rfc822-body-from_, binary=1 */
   'r','f','c','8','2','2','-','b','o','d','y','-','f','r','o','m','_','\0',
   /* 67. [862]+4 save, binary=1 */
   's','a','v','e','\0',
   /* 68. [867]+13 searchheaders, binary=1 */
   's','e','a','r','c','h','h','e','a','d','e','r','s','\0',
   /* 69. [881]+28 sendcharsets-else-ttycharset, binary=1 */
   's','e','n','d','c','h','a','r','s','e','t','s','-','e','l','s','e','-','t','t','y','c','h','a','r','s','e','t','\0',
   /* 70. [910]+8 sendwait, binary=1 */
   's','e','n','d','w','a','i','t','\0',
   /* 71. [919]+8 showlast, binary=1 */
   's','h','o','w','l','a','s','t','\0',
   /* 72. [928]+8 showname, binary=1 */
   's','h','o','w','n','a','m','e','\0',
   /* 73. [937]+6 showto, binary=1 */
   's','h','o','w','t','o','\0',
   /* 74. [944]+13 skipemptybody, binary=1 */
   's','k','i','p','e','m','p','t','y','b','o','d','y','\0',
   /* 75. [958]+22 smime-force-encryption, binary=1 */
   's','m','i','m','e','-','f','o','r','c','e','-','e','n','c','r','y','p','t','i','o','n','\0',
   /* 76. [981]+19 smime-no-default-ca, binary=1 */
   's','m','i','m','e','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 77. [1001]+10 smime-sign, binary=1 */
   's','m','i','m','e','-','s','i','g','n','\0',
   /* 78. [1012]+17 smtp-use-starttls, binary=1 */
   's','m','t','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 79. [1030]+17 ssl-no-default-ca, binary=1 */
   's','s','l','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 80. [1048]+12 ssl-v2-allow, binary=1 */
   's','s','l','-','v','2','-','a','l','l','o','w','\0',
   /* 81. [1061]+15 writebackedited, binary=1 */
   'w','r','i','t','e','b','a','c','k','e','d','i','t','e','d','\0',
   /* 82. [1077]+7 verbose, binary=1 */
   'v','e','r','b','o','s','e','\0',
   /* 83. [1085]+8 attrlist, binary=0 */
   'a','t','t','r','l','i','s','t','\0',
   /* 84. [1094]+7 autobcc, binary=0 */
   'a','u','t','o','b','c','c','\0',
   /* 85. [1102]+6 autocc, binary=0 */
   'a','u','t','o','c','c','\0',
   /* 86. [1109]+7 autoinc, binary=0 */
   'a','u','t','o','i','n','c','\0',
   /* 87. [1117]+8 autosort, binary=0 */
   'a','u','t','o','s','o','r','t','\0',
   /* 88. [1126]+12 charset-7bit, binary=0 */
   'c','h','a','r','s','e','t','-','7','b','i','t','\0',
   /* 89. [1139]+12 charset-8bit, binary=0 */
   'c','h','a','r','s','e','t','-','8','b','i','t','\0',
   /* 90. [1152]+3 cmd, binary=0 */
   'c','m','d','\0',
   /* 91. [1156]+13 colour-pagers, binary=0 */
   'c','o','l','o','u','r','-','p','a','g','e','r','s','\0',
   /* 92. [1170]+12 colour-from_, binary=0 */
   'c','o','l','o','u','r','-','f','r','o','m','_','\0',
   /* 93. [1183]+13 colour-header, binary=0 */
   'c','o','l','o','u','r','-','h','e','a','d','e','r','\0',
   /* 94. [1197]+14 colour-msginfo, binary=0 */
   'c','o','l','o','u','r','-','m','s','g','i','n','f','o','\0',
   /* 95. [1212]+15 colour-partinfo, binary=0 */
   'c','o','l','o','u','r','-','p','a','r','t','i','n','f','o','\0',
   /* 96. [1228]+12 colour-terms, binary=0 */
   'c','o','l','o','u','r','-','t','e','r','m','s','\0',
   /* 97. [1241]+14 colour-uheader, binary=0 */
   'c','o','l','o','u','r','-','u','h','e','a','d','e','r','\0',
   /* 98. [1256]+19 colour-user-headers, binary=0 */
   'c','o','l','o','u','r','-','u','s','e','r','-','h','e','a','d','e','r','s','\0',
   /* 99. [1276]+3 crt, binary=0 */
   'c','r','t','\0',
   /* 100. [1280]+9 datefield, binary=0 */
   'd','a','t','e','f','i','e','l','d','\0',
   /* 101. [1290]+23 datefield-markout-older, binary=0 */
   'd','a','t','e','f','i','e','l','d','-','m','a','r','k','o','u','t','-','o','l','d','e','r','\0',
   /* 102. [1314]+4 DEAD, binary=0 */
   'D','E','A','D','\0',
   /* 103. [1319]+6 EDITOR, binary=0 */
   'E','D','I','T','O','R','\0',
   /* 104. [1326]+8 encoding, binary=0 */
   'e','n','c','o','d','i','n','g','\0',
   /* 105. [1335]+6 escape, binary=0 */
   'e','s','c','a','p','e','\0',
   /* 106. [1342]+6 folder, binary=0 */
   'f','o','l','d','e','r','\0',
   /* 107. [1349]+11 folder-hook, binary=0 */
   'f','o','l','d','e','r','-','h','o','o','k','\0',
   /* 108. [1361]+4 from, binary=0 */
   'f','r','o','m','\0',
   /* 109. [1366]+10 fwdheading, binary=0 */
   'f','w','d','h','e','a','d','i','n','g','\0',
   /* 110. [1377]+8 headline, binary=0 */
   'h','e','a','d','l','i','n','e','\0',
   /* 111. [1386]+8 hostname, binary=0 */
   'h','o','s','t','n','a','m','e','\0',
   /* 112. [1395]+9 imap-auth, binary=0 */
   'i','m','a','p','-','a','u','t','h','\0',
   /* 113. [1405]+10 imap-cache, binary=0 */
   'i','m','a','p','-','c','a','c','h','e','\0',
   /* 114. [1416]+14 imap-keepalive, binary=0 */
   'i','m','a','p','-','k','e','e','p','a','l','i','v','e','\0',
   /* 115. [1431]+15 imap-list-depth, binary=0 */
   'i','m','a','p','-','l','i','s','t','-','d','e','p','t','h','\0',
   /* 116. [1447]+12 indentprefix, binary=0 */
   'i','n','d','e','n','t','p','r','e','f','i','x','\0',
   /* 117. [1460]+24 line-editor-cursor-right, binary=0 */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','u','r','s','o','r','-','r','i','g','h','t','\0',
   /* 118. [1485]+6 LISTER, binary=0 */
   'L','I','S','T','E','R','\0',
   /* 119. [1492]+4 MAIL, binary=0 */
   'M','A','I','L','\0',
   /* 120. [1497]+4 MBOX, binary=0 */
   'M','B','O','X','\0',
   /* 121. [1502]+22 mimetypes-load-control, binary=0 */
   'm','i','m','e','t','y','p','e','s','-','l','o','a','d','-','c','o','n','t','r','o','l','\0',
   /* 122. [1525]+13 NAIL_EXTRA_RC, binary=0 */
   'N','A','I','L','_','E','X','T','R','A','_','R','C','\0',
   /* 123. [1539]+9 NAIL_HEAD, binary=0 */
   'N','A','I','L','_','H','E','A','D','\0',
   /* 124. [1549]+13 NAIL_HISTFILE, binary=0 */
   'N','A','I','L','_','H','I','S','T','F','I','L','E','\0',
   /* 125. [1563]+13 NAIL_HISTSIZE, binary=0 */
   'N','A','I','L','_','H','I','S','T','S','I','Z','E','\0',
   /* 126. [1577]+9 NAIL_TAIL, binary=0 */
   'N','A','I','L','_','T','A','I','L','\0',
   /* 127. [1587]+10 newfolders, binary=0 */
   'n','e','w','f','o','l','d','e','r','s','\0',
   /* 128. [1598]+7 newmail, binary=0 */
   'n','e','w','m','a','i','l','\0',
   /* 129. [1606]+12 ORGANIZATION, binary=0 */
   'O','R','G','A','N','I','Z','A','T','I','O','N','\0',
   /* 130. [1619]+5 PAGER, binary=0 */
   'P','A','G','E','R','\0',
   /* 131. [1625]+14 pop3-keepalive, binary=0 */
   'p','o','p','3','-','k','e','e','p','a','l','i','v','e','\0',
   /* 132. [1640]+6 prompt, binary=0 */
   'p','r','o','m','p','t','\0',
   /* 133. [1647]+5 quote, binary=0 */
   'q','u','o','t','e','\0',
   /* 134. [1653]+10 quote-fold, binary=0 */
   'q','u','o','t','e','-','f','o','l','d','\0',
   /* 135. [1664]+6 record, binary=0 */
   'r','e','c','o','r','d','\0',
   /* 136. [1671]+7 replyto, binary=0 */
   'r','e','p','l','y','t','o','\0',
   /* 137. [1679]+6 screen, binary=0 */
   's','c','r','e','e','n','\0',
   /* 138. [1686]+12 sendcharsets, binary=0 */
   's','e','n','d','c','h','a','r','s','e','t','s','\0',
   /* 139. [1699]+6 sender, binary=0 */
   's','e','n','d','e','r','\0',
   /* 140. [1706]+8 sendmail, binary=0 */
   's','e','n','d','m','a','i','l','\0',
   /* 141. [1715]+17 sendmail-progname, binary=0 */
   's','e','n','d','m','a','i','l','-','p','r','o','g','n','a','m','e','\0',
   /* 142. [1733]+5 SHELL, binary=0 */
   'S','H','E','L','L','\0',
   /* 143. [1739]+4 Sign, binary=0 */
   'S','i','g','n','\0',
   /* 144. [1744]+4 sign, binary=0 */
   's','i','g','n','\0',
   /* 145. [1749]+9 signature, binary=0 */
   's','i','g','n','a','t','u','r','e','\0',
   /* 146. [1759]+12 smime-ca-dir, binary=0 */
   's','m','i','m','e','-','c','a','-','d','i','r','\0',
   /* 147. [1772]+13 smime-ca-file, binary=0 */
   's','m','i','m','e','-','c','a','-','f','i','l','e','\0',
   /* 148. [1786]+13 smime-crl-dir, binary=0 */
   's','m','i','m','e','-','c','r','l','-','d','i','r','\0',
   /* 149. [1800]+14 smime-crl-file, binary=0 */
   's','m','i','m','e','-','c','r','l','-','f','i','l','e','\0',
   /* 150. [1815]+15 smime-sign-cert, binary=0 */
   's','m','i','m','e','-','s','i','g','n','-','c','e','r','t','\0',
   /* 151. [1831]+24 smime-sign-include-certs, binary=0 */
   's','m','i','m','e','-','s','i','g','n','-','i','n','c','l','u','d','e','-','c','e','r','t','s','\0',
   /* 152. [1856]+4 smtp, binary=0 */
   's','m','t','p','\0',
   /* 153. [1861]+9 smtp-auth, binary=0 */
   's','m','t','p','-','a','u','t','h','\0',
   /* 154. [1871]+18 smtp-auth-password, binary=0 */
   's','m','t','p','-','a','u','t','h','-','p','a','s','s','w','o','r','d','\0',
   /* 155. [1890]+14 smtp-auth-user, binary=0 */
   's','m','t','p','-','a','u','t','h','-','u','s','e','r','\0',
   /* 156. [1905]+12 spam-command, binary=0 */
   's','p','a','m','-','c','o','m','m','a','n','d','\0',
   /* 157. [1918]+9 spam-host, binary=0 */
   's','p','a','m','-','h','o','s','t','\0',
   /* 158. [1928]+12 spam-maxsize, binary=0 */
   's','p','a','m','-','m','a','x','s','i','z','e','\0',
   /* 159. [1941]+9 spam-port, binary=0 */
   's','p','a','m','-','p','o','r','t','\0',
   /* 160. [1951]+11 spam-socket, binary=0 */
   's','p','a','m','-','s','o','c','k','e','t','\0',
   /* 161. [1963]+9 spam-user, binary=0 */
   's','p','a','m','-','u','s','e','r','\0',
   /* 162. [1973]+10 ssl-ca-dir, binary=0 */
   's','s','l','-','c','a','-','d','i','r','\0',
   /* 163. [1984]+11 ssl-ca-file, binary=0 */
   's','s','l','-','c','a','-','f','i','l','e','\0',
   /* 164. [1996]+8 ssl-cert, binary=0 */
   's','s','l','-','c','e','r','t','\0',
   /* 165. [2005]+15 ssl-cipher-list, binary=0 */
   's','s','l','-','c','i','p','h','e','r','-','l','i','s','t','\0',
   /* 166. [2021]+11 ssl-crl-dir, binary=0 */
   's','s','l','-','c','r','l','-','d','i','r','\0',
   /* 167. [2033]+12 ssl-crl-file, binary=0 */
   's','s','l','-','c','r','l','-','f','i','l','e','\0',
   /* 168. [2046]+7 ssl-key, binary=0 */
   's','s','l','-','k','e','y','\0',
   /* 169. [2054]+10 ssl-method, binary=0 */
   's','s','l','-','m','e','t','h','o','d','\0',
   /* 170. [2065]+12 ssl-rand-egd, binary=0 */
   's','s','l','-','r','a','n','d','-','e','g','d','\0',
   /* 171. [2078]+13 ssl-rand-file, binary=0 */
   's','s','l','-','r','a','n','d','-','f','i','l','e','\0',
   /* 172. [2092]+10 ssl-verify, binary=0 */
   's','s','l','-','v','e','r','i','f','y','\0',
   /* 173. [2103]+10 stealthmua, binary=0 */
   's','t','e','a','l','t','h','m','u','a','\0',
   /* 174. [2114]+8 toplines, binary=0 */
   't','o','p','l','i','n','e','s','\0',
   /* 175. [2123]+10 ttycharset, binary=0 */
   't','t','y','c','h','a','r','s','e','t','\0',
   /* 176. [2134]+6 VISUAL, binary=0 */
   'V','I','S','U','A','L','\0',
};

static struct var_map const _var_map[] = {
   /* ok_b_add_file_recipients */ {3722159545u, 0u, 1, 0},
   /* ok_b_allnet */ {3928217024u, 20u, 1, 0},
   /* ok_b_append */ {3933094936u, 27u, 1, 0},
   /* ok_b_ask */ {109535u, 34u, 1, 0},
   /* ok_b_askatend */ {437227595u, 38u, 1, 0},
   /* ok_b_askattach */ {1544133716u, 47u, 1, 0},
   /* ok_b_askbcc */ {3936469383u, 57u, 1, 0},
   /* ok_b_askcc */ {119286981u, 64u, 1, 0},
   /* ok_b_asksign */ {1055088464u, 70u, 1, 0},
   /* ok_b_asksub */ {3936488489u, 78u, 1, 0},
   /* ok_b_attachment_ask_content_description */ {1653823630u, 85u, 1, 0},
   /* ok_b_attachment_ask_content_disposition */ {2717622527u, 120u, 1, 0},
   /* ok_b_attachment_ask_content_id */ {1759766423u, 155u, 1, 0},
   /* ok_b_attachment_ask_content_type */ {830642604u, 181u, 1, 0},
   /* ok_b_autocollapse */ {2551200844u, 209u, 1, 0},
   /* ok_b_autoprint */ {163072614u, 222u, 1, 0},
   /* ok_b_autothread */ {1231424433u, 232u, 1, 0},
   /* ok_b_bang */ {3631192u, 243u, 1, 0},
   /* ok_b_batch_exit_on_error */ {625280330u, 248u, 1, 0},
   /* ok_b_bsdannounce */ {170960u, 268u, 1, 0},
   /* ok_b_bsdcompat */ {3120210877u, 280u, 1, 0},
   /* ok_b_bsdflags */ {4132654694u, 290u, 1, 0},
   /* ok_b_bsdheadline */ {2716084787u, 299u, 1, 0},
   /* ok_b_bsdmsgs */ {2338050259u, 311u, 1, 0},
   /* ok_b_bsdorder */ {4143546805u, 319u, 1, 0},
   /* ok_b_bsdset */ {3975371813u, 328u, 1, 0},
   /* ok_b_colour_disable */ {482327989u, 335u, 1, 0},
   /* ok_b_debug */ {122332423u, 350u, 1, 1},
   /* ok_b_disconnected */ {989496243u, 356u, 1, 0},
   /* ok_b_dot */ {112679u, 369u, 1, 0},
   /* ok_b_editalong */ {3877730807u, 373u, 1, 0},
   /* ok_b_editheaders */ {1055429730u, 383u, 1, 0},
   /* ok_b_emptybox */ {171820376u, 395u, 1, 0},
   /* ok_b_emptystart */ {2449114909u, 404u, 1, 0},
   /* ok_b_flipr */ {124963293u, 415u, 1, 0},
   /* ok_b_forward_as_attachment */ {2102400300u, 421u, 1, 0},
   /* ok_b_fullnames */ {3777473511u, 443u, 1, 0},
   /* ok_b_header */ {4193457129u, 453u, 1, 1},
   /* ok_b_hold */ {3861991u, 460u, 1, 0},
   /* ok_b_idna_disable */ {2723216029u, 465u, 1, 0},
   /* ok_b_ignore */ {4235443940u, 478u, 1, 0},
   /* ok_b_ignoreeof */ {4097949886u, 485u, 1, 0},
   /* ok_b_imap_use_starttls */ {1934791407u, 495u, 1, 0},
   /* ok_b_keep */ {3958693u, 513u, 1, 0},
   /* ok_b_keep_content_length */ {3727474588u, 518u, 1, 0},
   /* ok_b_keepsave */ {302149108u, 538u, 1, 0},
   /* ok_b_line_editor_disable */ {4215099357u, 547u, 1, 0},
   /* ok_b_markanswered */ {2312309028u, 567u, 1, 0},
   /* ok_b_message_id_disable */ {130334368u, 580u, 1, 0},
   /* ok_b_metoo */ {133025124u, 599u, 1, 0},
   /* ok_b_mime_allow_text_controls */ {3414355303u, 605u, 1, 0},
   /* ok_b_mime_counter_evidence */ {3192709189u, 630u, 1, 0},
   /* ok_b_outfolder */ {1400017300u, 652u, 1, 0},
   /* ok_b_page */ {4134077u, 662u, 1, 0},
   /* ok_b_piperaw */ {2861320984u, 667u, 1, 0},
   /* ok_b_pop3_bulk_load */ {275342634u, 675u, 1, 0},
   /* ok_b_pop3_no_apop */ {3632267817u, 690u, 1, 0},
   /* ok_b_pop3_use_starttls */ {43237290u, 703u, 1, 0},
   /* ok_b_print_all_chars */ {1156901649u, 721u, 1, 0},
   /* ok_b_print_alternatives */ {1388395788u, 737u, 1, 0},
   /* ok_b_quiet */ {138331496u, 756u, 1, 0},
   /* ok_b_quote_as_attachment */ {3820786885u, 762u, 1, 0},
   /* ok_b_recipients_in_cc */ {682388781u, 782u, 1, 0},
   /* ok_b_record_resent */ {3191066333u, 799u, 1, 0},
   /* ok_b_reply_in_same_charset */ {3710195994u, 813u, 1, 0},
   /* ok_b_Replyall */ {418925029u, 835u, 1, 0},
   /* ok_b_rfc822_body_from_ */ {145783858u, 844u, 1, 0},
   /* ok_b_save */ {4242383u, 862u, 1, 0},
   /* ok_b_searchheaders */ {2344495826u, 867u, 1, 0},
   /* ok_b_sendcharsets_else_ttycharset */ {259282709u, 881u, 1, 0},
   /* ok_b_sendwait */ {2285407359u, 910u, 1, 0},
   /* ok_b_showlast */ {1926116885u, 919u, 1, 0},
   /* ok_b_showname */ {1926188546u, 928u, 1, 0},
   /* ok_b_showto */ {333061220u, 937u, 1, 0},
   /* ok_b_skipemptybody */ {3875901652u, 944u, 1, 1},
   /* ok_b_smime_force_encryption */ {3116904399u, 958u, 1, 0},
   /* ok_b_smime_no_default_ca */ {3384448360u, 981u, 1, 0},
   /* ok_b_smime_sign */ {105885657u, 1001u, 1, 0},
   /* ok_b_smtp_use_starttls */ {1310886988u, 1012u, 1, 0},
   /* ok_b_ssl_no_default_ca */ {1961350591u, 1030u, 1, 0},
   /* ok_b_ssl_v2_allow */ {1939207059u, 1048u, 1, 0},
   /* ok_b_writebackedited */ {3469190955u, 1061u, 1, 0},
   /* ok_b_verbose */ {1865913974u, 1077u, 1, 1},
   /* ok_v_attrlist */ {2100791799u, 1085u, 0, 0},
   /* ok_v_autobcc */ {1143881025u, 1094u, 0, 0},
   /* ok_v_autocc */ {3939178815u, 1102u, 0, 0},
   /* ok_v_autoinc */ {1143889011u, 1109u, 0, 0},
   /* ok_v_autosort */ {3388960065u, 1117u, 0, 0},
   /* ok_v_charset_7bit */ {358823789u, 1126u, 0, 0},
   /* ok_v_charset_8bit */ {358859726u, 1139u, 0, 0},
   /* ok_v_cmd */ {111508u, 1152u, 0, 0},
   /* ok_v_colour_pagers */ {4118541667u, 1156u, 0, 0},
   /* ok_v_colour_from_ */ {2846725972u, 1170u, 0, 0},
   /* ok_v_colour_header */ {3809985066u, 1183u, 0, 0},
   /* ok_v_colour_msginfo */ {3893028372u, 1197u, 0, 0},
   /* ok_v_colour_partinfo */ {1593971076u, 1212u, 0, 0},
   /* ok_v_colour_terms */ {2862864972u, 1228u, 0, 0},
   /* ok_v_colour_uheader */ {906710655u, 1241u, 0, 0},
   /* ok_v_colour_user_headers */ {1414874633u, 1256u, 0, 0},
   /* ok_v_crt */ {111689u, 1276u, 0, 0},
   /* ok_v_datefield */ {3657134018u, 1280u, 0, 0},
   /* ok_v_datefield_markout_older */ {2384089013u, 1290u, 0, 0},
   /* ok_v_DEAD */ {2521070u, 1314u, 0, 0},
   /* ok_v_EDITOR */ {2783702311u, 1319u, 0, 0},
   /* ok_v_encoding */ {947851527u, 1326u, 0, 0},
   /* ok_v_escape */ {4092722801u, 1335u, 0, 0},
   /* ok_v_folder */ {4127440860u, 1342u, 0, 1},
   /* ok_v_folder_hook */ {3184215642u, 1349u, 0, 0},
   /* ok_v_from */ {3793492u, 1361u, 0, 0},
   /* ok_v_fwdheading */ {1142629489u, 1366u, 0, 0},
   /* ok_v_headline */ {1124823322u, 1377u, 0, 0},
   /* ok_v_hostname */ {1878076063u, 1386u, 0, 0},
   /* ok_v_imap_auth */ {2458536262u, 1395u, 0, 0},
   /* ok_v_imap_cache */ {3823920008u, 1405u, 0, 0},
   /* ok_v_imap_keepalive */ {75507402u, 1416u, 0, 0},
   /* ok_v_imap_list_depth */ {270835474u, 1431u, 0, 0},
   /* ok_v_indentprefix */ {1578583856u, 1447u, 0, 0},
   /* ok_v_line_editor_cursor_right */ {1667489426u, 1460u, 0, 1},
   /* ok_v_LISTER */ {3063938707u, 1485u, 0, 0},
   /* ok_v_MAIL */ {2840419u, 1492u, 0, 0},
   /* ok_v_MBOX */ {2841718u, 1497u, 0, 0},
   /* ok_v_mimetypes_load_control */ {1028657528u, 1502u, 0, 0},
   /* ok_v_NAIL_EXTRA_RC */ {4280681563u, 1525u, 0, 0},
   /* ok_v_NAIL_HEAD */ {639934357u, 1539u, 0, 0},
   /* ok_v_NAIL_HISTFILE */ {1058233243u, 1549u, 0, 0},
   /* ok_v_NAIL_HISTSIZE */ {1058700886u, 1563u, 0, 0},
   /* ok_v_NAIL_TAIL */ {640361517u, 1577u, 0, 0},
   /* ok_v_newfolders */ {985178617u, 1587u, 0, 0},
   /* ok_v_newmail */ {130414157u, 1598u, 0, 0},
   /* ok_v_ORGANIZATION */ {1265947381u, 1606u, 0, 0},
   /* ok_v_PAGER */ {97289263u, 1619u, 0, 0},
   /* ok_v_pop3_keepalive */ {1495995749u, 1625u, 0, 0},
   /* ok_v_prompt */ {227503234u, 1640u, 0, 0},
   /* ok_v_quote */ {138338510u, 1647u, 0, 0},
   /* ok_v_quote_fold */ {1182381408u, 1653u, 0, 0},
   /* ok_v_record */ {289928031u, 1664u, 0, 0},
   /* ok_v_replyto */ {993007855u, 1671u, 0, 0},
   /* ok_v_screen */ {327219328u, 1679u, 0, 0},
   /* ok_v_sendcharsets */ {1707020871u, 1686u, 0, 0},
   /* ok_v_sender */ {329446337u, 1699u, 0, 0},
   /* ok_v_sendmail */ {2285047981u, 1706u, 0, 0},
   /* ok_v_sendmail_progname */ {4267157331u, 1715u, 0, 0},
   /* ok_v_SHELL */ {101096632u, 1733u, 0, 0},
   /* ok_v_Sign */ {3100625u, 1739u, 0, 0},
   /* ok_v_sign */ {4250609u, 1744u, 0, 0},
   /* ok_v_signature */ {994697266u, 1749u, 0, 0},
   /* ok_v_smime_ca_dir */ {3002585464u, 1759u, 0, 0},
   /* ok_v_smime_ca_file */ {301144281u, 1772u, 0, 0},
   /* ok_v_smime_crl_dir */ {1039105045u, 1786u, 0, 0},
   /* ok_v_smime_crl_file */ {4225767190u, 1800u, 0, 0},
   /* ok_v_smime_sign_cert */ {2215302260u, 1815u, 0, 0},
   /* ok_v_smime_sign_include_certs */ {1036659416u, 1831u, 0, 0},
   /* ok_v_smtp */ {4255396u, 1856u, 0, 0},
   /* ok_v_smtp_auth */ {3589879203u, 1861u, 0, 0},
   /* ok_v_smtp_auth_password */ {1996663907u, 1871u, 0, 0},
   /* ok_v_smtp_auth_user */ {2594939183u, 1890u, 0, 0},
   /* ok_v_spam_command */ {3457532253u, 1905u, 0, 0},
   /* ok_v_spam_host */ {3710940444u, 1918u, 0, 0},
   /* ok_v_spam_maxsize */ {2952684415u, 1928u, 0, 0},
   /* ok_v_spam_port */ {3711227907u, 1941u, 0, 0},
   /* ok_v_spam_socket */ {79825959u, 1951u, 0, 0},
   /* ok_v_spam_user */ {3711411517u, 1963u, 0, 0},
   /* ok_v_ssl_ca_dir */ {1179440559u, 1973u, 0, 0},
   /* ok_v_ssl_ca_file */ {266904560u, 1984u, 0, 0},
   /* ok_v_ssl_cert */ {3041879213u, 1996u, 0, 0},
   /* ok_v_ssl_cipher_list */ {2789248355u, 2005u, 0, 0},
   /* ok_v_ssl_crl_dir */ {1004865324u, 2021u, 0, 0},
   /* ok_v_ssl_crl_file */ {3095856397u, 2033u, 0, 0},
   /* ok_v_ssl_key */ {2825347880u, 2046u, 0, 0},
   /* ok_v_ssl_method */ {1578094240u, 2054u, 0, 0},
   /* ok_v_ssl_rand_egd */ {2083698465u, 2065u, 0, 0},
   /* ok_v_ssl_rand_file */ {42611089u, 2078u, 0, 0},
   /* ok_v_ssl_verify */ {1930241716u, 2092u, 0, 0},
   /* ok_v_stealthmua */ {4266102040u, 2103u, 0, 0},
   /* ok_v_toplines */ {2071224238u, 2114u, 0, 0},
   /* ok_v_ttycharset */ {113531019u, 2123u, 0, 0},
   /* ok_v_VISUAL */ {3455293588u, 2134u, 0, 0},
};

#define _VAR_REV_ILL         177u
#define _VAR_REV_PRIME       353u
#define _VAR_REV_LONGEST     5u
#define _VAR_REV_WRAPAROUND  0
static ui8_t const _var_revmap[_VAR_REV_PRIME] = {
   2u, 12u, 39u, 177u, 177u, 177u, 177u, 177u, 177u, 100u,
   106u, 177u, 177u, 177u, 177u, 177u, 177u, 177u, 118u, 177u,
   177u, 177u, 177u, 177u, 177u, 96u, 177u, 177u, 15u, 67u,
   4u, 117u, 132u, 21u, 44u, 158u, 177u, 36u, 30u, 176u,
   177u, 177u, 177u, 177u, 177u, 177u, 177u, 177u, 177u, 177u,
   177u, 177u, 177u, 177u, 177u, 177u, 177u, 8u, 84u, 54u,
   157u, 48u, 138u, 177u, 22u, 177u, 177u, 41u, 120u, 13u,
   177u, 177u, 29u, 73u, 123u, 128u, 35u, 129u, 177u, 177u,
   151u, 177u, 177u, 68u, 64u, 26u, 57u, 101u, 103u, 177u,
   177u, 177u, 177u, 177u, 53u, 127u, 177u, 32u, 177u, 82u,
   145u, 177u, 126u, 177u, 177u, 3u, 20u, 115u, 19u, 131u,
   171u, 177u, 0u, 177u, 177u, 177u, 177u, 177u, 110u, 177u,
   6u, 177u, 177u, 177u, 177u, 148u, 168u, 177u, 177u, 74u,
   77u, 177u, 177u, 177u, 18u, 46u, 11u, 144u, 162u, 141u,
   177u, 99u, 134u, 177u, 76u, 177u, 136u, 80u, 81u, 165u,
   97u, 43u, 177u, 66u, 98u, 108u, 87u, 167u, 177u, 177u,
   177u, 65u, 7u, 55u, 9u, 177u, 153u, 177u, 5u, 177u,
   45u, 16u, 38u, 42u, 177u, 177u, 177u, 155u, 28u, 47u,
   75u, 119u, 159u, 170u, 177u, 25u, 92u, 56u, 177u, 177u,
   177u, 177u, 59u, 177u, 177u, 1u, 83u, 177u, 177u, 177u,
   164u, 163u, 177u, 33u, 177u, 177u, 105u, 113u, 177u, 177u,
   177u, 177u, 177u, 177u, 177u, 177u, 177u, 177u, 175u, 177u,
   177u, 50u, 177u, 177u, 177u, 177u, 143u, 177u, 161u, 177u,
   125u, 177u, 177u, 177u, 17u, 34u, 122u, 177u, 52u, 177u,
   177u, 177u, 177u, 177u, 154u, 62u, 177u, 177u, 177u, 177u,
   177u, 49u, 177u, 177u, 177u, 177u, 142u, 177u, 177u, 109u,
   177u, 177u, 139u, 140u, 177u, 177u, 177u, 177u, 40u, 174u,
   177u, 177u, 71u, 27u, 10u, 72u, 58u, 85u, 86u, 89u,
   111u, 133u, 95u, 150u, 104u, 177u, 70u, 177u, 177u, 177u,
   177u, 177u, 93u, 146u, 177u, 177u, 23u, 102u, 172u, 91u,
   177u, 177u, 177u, 14u, 160u, 177u, 135u, 149u, 78u, 177u,
   177u, 61u, 124u, 90u, 177u, 177u, 177u, 177u, 173u, 177u,
   177u, 177u, 107u, 177u, 177u, 31u, 69u, 60u, 169u, 24u,
   137u, 156u, 116u, 177u, 147u, 152u, 37u, 51u, 177u, 112u,
   177u, 177u, 63u, 79u, 177u, 130u, 166u, 177u, 88u, 94u,
   114u, 121u, 177u
};
