/*@ okeys.h, generated by ./create-okey-map.pl on Thu May  8 13:23:50 2014.
 *@ See acmava.c for more */

static char const _var_keydat[] = {
   /* 0. [0]+19 add-file-recipients, binary=1 */
   'a','d','d','-','f','i','l','e','-','r','e','c','i','p','i','e','n','t','s','\0',
   /* 1. [20]+6 allnet, binary=1 */
   'a','l','l','n','e','t','\0',
   /* 2. [27]+6 append, binary=1 */
   'a','p','p','e','n','d','\0',
   /* 3. [34]+3 ask, binary=1 */
   'a','s','k','\0',
   /* 4. [38]+8 askatend, binary=1 */
   'a','s','k','a','t','e','n','d','\0',
   /* 5. [47]+9 askattach, binary=1 */
   'a','s','k','a','t','t','a','c','h','\0',
   /* 6. [57]+6 askbcc, binary=1 */
   'a','s','k','b','c','c','\0',
   /* 7. [64]+5 askcc, binary=1 */
   'a','s','k','c','c','\0',
   /* 8. [70]+7 asksign, binary=1 */
   'a','s','k','s','i','g','n','\0',
   /* 9. [78]+6 asksub, binary=1 */
   'a','s','k','s','u','b','\0',
   /* 10. [85]+34 attachment-ask-content-description, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','\0',
   /* 11. [120]+34 attachment-ask-content-disposition, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','d','i','s','p','o','s','i','t','i','o','n','\0',
   /* 12. [155]+25 attachment-ask-content-id, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','i','d','\0',
   /* 13. [181]+27 attachment-ask-content-type, binary=1 */
   'a','t','t','a','c','h','m','e','n','t','-','a','s','k','-','c','o','n','t','e','n','t','-','t','y','p','e','\0',
   /* 14. [209]+12 autocollapse, binary=1 */
   'a','u','t','o','c','o','l','l','a','p','s','e','\0',
   /* 15. [222]+9 autoprint, binary=1 */
   'a','u','t','o','p','r','i','n','t','\0',
   /* 16. [232]+10 autothread, binary=1 */
   'a','u','t','o','t','h','r','e','a','d','\0',
   /* 17. [243]+4 bang, binary=1 */
   'b','a','n','g','\0',
   /* 18. [248]+19 batch-exit-on-error, binary=1 */
   'b','a','t','c','h','-','e','x','i','t','-','o','n','-','e','r','r','o','r','\0',
   /* 19. [268]+11 bsdannounce, binary=1 */
   'b','s','d','a','n','n','o','u','n','c','e','\0',
   /* 20. [280]+9 bsdcompat, binary=1 */
   'b','s','d','c','o','m','p','a','t','\0',
   /* 21. [290]+8 bsdflags, binary=1 */
   'b','s','d','f','l','a','g','s','\0',
   /* 22. [299]+11 bsdheadline, binary=1 */
   'b','s','d','h','e','a','d','l','i','n','e','\0',
   /* 23. [311]+7 bsdmsgs, binary=1 */
   'b','s','d','m','s','g','s','\0',
   /* 24. [319]+8 bsdorder, binary=1 */
   'b','s','d','o','r','d','e','r','\0',
   /* 25. [328]+6 bsdset, binary=1 */
   'b','s','d','s','e','t','\0',
   /* 26. [335]+14 colour-disable, binary=1 */
   'c','o','l','o','u','r','-','d','i','s','a','b','l','e','\0',
   /* 27. [350]+5 debug, binary=1 */
   'd','e','b','u','g','\0',
   /* 28. [356]+12 disconnected, binary=1 */
   'd','i','s','c','o','n','n','e','c','t','e','d','\0',
   /* 29. [369]+3 dot, binary=1 */
   'd','o','t','\0',
   /* 30. [373]+9 editalong, binary=1 */
   'e','d','i','t','a','l','o','n','g','\0',
   /* 31. [383]+11 editheaders, binary=1 */
   'e','d','i','t','h','e','a','d','e','r','s','\0',
   /* 32. [395]+8 emptybox, binary=1 */
   'e','m','p','t','y','b','o','x','\0',
   /* 33. [404]+10 emptystart, binary=1 */
   'e','m','p','t','y','s','t','a','r','t','\0',
   /* 34. [415]+5 flipr, binary=1 */
   'f','l','i','p','r','\0',
   /* 35. [421]+21 forward-as-attachment, binary=1 */
   'f','o','r','w','a','r','d','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 36. [443]+9 fullnames, binary=1 */
   'f','u','l','l','n','a','m','e','s','\0',
   /* 37. [453]+6 header, binary=1 */
   'h','e','a','d','e','r','\0',
   /* 38. [460]+4 hold, binary=1 */
   'h','o','l','d','\0',
   /* 39. [465]+12 idna-disable, binary=1 */
   'i','d','n','a','-','d','i','s','a','b','l','e','\0',
   /* 40. [478]+6 ignore, binary=1 */
   'i','g','n','o','r','e','\0',
   /* 41. [485]+9 ignoreeof, binary=1 */
   'i','g','n','o','r','e','e','o','f','\0',
   /* 42. [495]+17 imap-use-starttls, binary=1 */
   'i','m','a','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 43. [513]+4 keep, binary=1 */
   'k','e','e','p','\0',
   /* 44. [518]+19 keep-content-length, binary=1 */
   'k','e','e','p','-','c','o','n','t','e','n','t','-','l','e','n','g','t','h','\0',
   /* 45. [538]+8 keepsave, binary=1 */
   'k','e','e','p','s','a','v','e','\0',
   /* 46. [547]+19 line-editor-disable, binary=1 */
   'l','i','n','e','-','e','d','i','t','o','r','-','d','i','s','a','b','l','e','\0',
   /* 47. [567]+12 markanswered, binary=1 */
   'm','a','r','k','a','n','s','w','e','r','e','d','\0',
   /* 48. [580]+18 message-id-disable, binary=1 */
   'm','e','s','s','a','g','e','-','i','d','-','d','i','s','a','b','l','e','\0',
   /* 49. [599]+5 metoo, binary=1 */
   'm','e','t','o','o','\0',
   /* 50. [605]+24 mime-allow-text-controls, binary=1 */
   'm','i','m','e','-','a','l','l','o','w','-','t','e','x','t','-','c','o','n','t','r','o','l','s','\0',
   /* 51. [630]+21 mime-counter-evidence, binary=1 */
   'm','i','m','e','-','c','o','u','n','t','e','r','-','e','v','i','d','e','n','c','e','\0',
   /* 52. [652]+9 outfolder, binary=1 */
   'o','u','t','f','o','l','d','e','r','\0',
   /* 53. [662]+4 page, binary=1 */
   'p','a','g','e','\0',
   /* 54. [667]+7 piperaw, binary=1 */
   'p','i','p','e','r','a','w','\0',
   /* 55. [675]+14 pop3-bulk-load, binary=1 */
   'p','o','p','3','-','b','u','l','k','-','l','o','a','d','\0',
   /* 56. [690]+12 pop3-no-apop, binary=1 */
   'p','o','p','3','-','n','o','-','a','p','o','p','\0',
   /* 57. [703]+17 pop3-use-starttls, binary=1 */
   'p','o','p','3','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 58. [721]+15 print-all-chars, binary=1 */
   'p','r','i','n','t','-','a','l','l','-','c','h','a','r','s','\0',
   /* 59. [737]+18 print-alternatives, binary=1 */
   'p','r','i','n','t','-','a','l','t','e','r','n','a','t','i','v','e','s','\0',
   /* 60. [756]+5 quiet, binary=1 */
   'q','u','i','e','t','\0',
   /* 61. [762]+19 quote-as-attachment, binary=1 */
   'q','u','o','t','e','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 62. [782]+16 recipients-in-cc, binary=1 */
   'r','e','c','i','p','i','e','n','t','s','-','i','n','-','c','c','\0',
   /* 63. [799]+13 record-resent, binary=1 */
   'r','e','c','o','r','d','-','r','e','s','e','n','t','\0',
   /* 64. [813]+21 reply-in-same-charset, binary=1 */
   'r','e','p','l','y','-','i','n','-','s','a','m','e','-','c','h','a','r','s','e','t','\0',
   /* 65. [835]+8 Replyall, binary=1 */
   'R','e','p','l','y','a','l','l','\0',
   /* 66. [844]+17 rfc822-body-from_, binary=1 */
   'r','f','c','8','2','2','-','b','o','d','y','-','f','r','o','m','_','\0',
   /* 67. [862]+4 save, binary=1 */
   's','a','v','e','\0',
   /* 68. [867]+13 searchheaders, binary=1 */
   's','e','a','r','c','h','h','e','a','d','e','r','s','\0',
   /* 69. [881]+28 sendcharsets-else-ttycharset, binary=1 */
   's','e','n','d','c','h','a','r','s','e','t','s','-','e','l','s','e','-','t','t','y','c','h','a','r','s','e','t','\0',
   /* 70. [910]+8 sendwait, binary=1 */
   's','e','n','d','w','a','i','t','\0',
   /* 71. [919]+8 showlast, binary=1 */
   's','h','o','w','l','a','s','t','\0',
   /* 72. [928]+8 showname, binary=1 */
   's','h','o','w','n','a','m','e','\0',
   /* 73. [937]+6 showto, binary=1 */
   's','h','o','w','t','o','\0',
   /* 74. [944]+13 skipemptybody, binary=1 */
   's','k','i','p','e','m','p','t','y','b','o','d','y','\0',
   /* 75. [958]+22 smime-force-encryption, binary=1 */
   's','m','i','m','e','-','f','o','r','c','e','-','e','n','c','r','y','p','t','i','o','n','\0',
   /* 76. [981]+19 smime-no-default-ca, binary=1 */
   's','m','i','m','e','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 77. [1001]+10 smime-sign, binary=1 */
   's','m','i','m','e','-','s','i','g','n','\0',
   /* 78. [1012]+17 smtp-use-starttls, binary=1 */
   's','m','t','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 79. [1030]+17 ssl-no-default-ca, binary=1 */
   's','s','l','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 80. [1048]+12 ssl-v2-allow, binary=1 */
   's','s','l','-','v','2','-','a','l','l','o','w','\0',
   /* 81. [1061]+10 v15-compat, binary=1 */
   'v','1','5','-','c','o','m','p','a','t','\0',
   /* 82. [1072]+7 verbose, binary=1 */
   'v','e','r','b','o','s','e','\0',
   /* 83. [1080]+15 writebackedited, binary=1 */
   'w','r','i','t','e','b','a','c','k','e','d','i','t','e','d','\0',
   /* 84. [1096]+8 attrlist, binary=0 */
   'a','t','t','r','l','i','s','t','\0',
   /* 85. [1105]+7 autobcc, binary=0 */
   'a','u','t','o','b','c','c','\0',
   /* 86. [1113]+6 autocc, binary=0 */
   'a','u','t','o','c','c','\0',
   /* 87. [1120]+8 autosort, binary=0 */
   'a','u','t','o','s','o','r','t','\0',
   /* 88. [1129]+12 charset-7bit, binary=0 */
   'c','h','a','r','s','e','t','-','7','b','i','t','\0',
   /* 89. [1142]+12 charset-8bit, binary=0 */
   'c','h','a','r','s','e','t','-','8','b','i','t','\0',
   /* 90. [1155]+3 cmd, binary=0 */
   'c','m','d','\0',
   /* 91. [1159]+13 colour-pagers, binary=0 */
   'c','o','l','o','u','r','-','p','a','g','e','r','s','\0',
   /* 92. [1173]+12 colour-from_, binary=0 */
   'c','o','l','o','u','r','-','f','r','o','m','_','\0',
   /* 93. [1186]+13 colour-header, binary=0 */
   'c','o','l','o','u','r','-','h','e','a','d','e','r','\0',
   /* 94. [1200]+14 colour-msginfo, binary=0 */
   'c','o','l','o','u','r','-','m','s','g','i','n','f','o','\0',
   /* 95. [1215]+15 colour-partinfo, binary=0 */
   'c','o','l','o','u','r','-','p','a','r','t','i','n','f','o','\0',
   /* 96. [1231]+12 colour-terms, binary=0 */
   'c','o','l','o','u','r','-','t','e','r','m','s','\0',
   /* 97. [1244]+14 colour-uheader, binary=0 */
   'c','o','l','o','u','r','-','u','h','e','a','d','e','r','\0',
   /* 98. [1259]+19 colour-user-headers, binary=0 */
   'c','o','l','o','u','r','-','u','s','e','r','-','h','e','a','d','e','r','s','\0',
   /* 99. [1279]+3 crt, binary=0 */
   'c','r','t','\0',
   /* 100. [1283]+9 datefield, binary=0 */
   'd','a','t','e','f','i','e','l','d','\0',
   /* 101. [1293]+23 datefield-markout-older, binary=0 */
   'd','a','t','e','f','i','e','l','d','-','m','a','r','k','o','u','t','-','o','l','d','e','r','\0',
   /* 102. [1317]+4 DEAD, binary=0 */
   'D','E','A','D','\0',
   /* 103. [1322]+6 EDITOR, binary=0 */
   'E','D','I','T','O','R','\0',
   /* 104. [1329]+8 encoding, binary=0 */
   'e','n','c','o','d','i','n','g','\0',
   /* 105. [1338]+6 escape, binary=0 */
   'e','s','c','a','p','e','\0',
   /* 106. [1345]+6 folder, binary=0 */
   'f','o','l','d','e','r','\0',
   /* 107. [1352]+11 folder-hook, binary=0 */
   'f','o','l','d','e','r','-','h','o','o','k','\0',
   /* 108. [1364]+4 from, binary=0 */
   'f','r','o','m','\0',
   /* 109. [1369]+10 fwdheading, binary=0 */
   'f','w','d','h','e','a','d','i','n','g','\0',
   /* 110. [1380]+8 headline, binary=0 */
   'h','e','a','d','l','i','n','e','\0',
   /* 111. [1389]+8 hostname, binary=0 */
   'h','o','s','t','n','a','m','e','\0',
   /* 112. [1398]+9 imap-auth, binary=0 */
   'i','m','a','p','-','a','u','t','h','\0',
   /* 113. [1408]+10 imap-cache, binary=0 */
   'i','m','a','p','-','c','a','c','h','e','\0',
   /* 114. [1419]+14 imap-keepalive, binary=0 */
   'i','m','a','p','-','k','e','e','p','a','l','i','v','e','\0',
   /* 115. [1434]+15 imap-list-depth, binary=0 */
   'i','m','a','p','-','l','i','s','t','-','d','e','p','t','h','\0',
   /* 116. [1450]+12 indentprefix, binary=0 */
   'i','n','d','e','n','t','p','r','e','f','i','x','\0',
   /* 117. [1463]+24 line-editor-cursor-right, binary=0 */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','u','r','s','o','r','-','r','i','g','h','t','\0',
   /* 118. [1488]+6 LISTER, binary=0 */
   'L','I','S','T','E','R','\0',
   /* 119. [1495]+4 MAIL, binary=0 */
   'M','A','I','L','\0',
   /* 120. [1500]+4 MBOX, binary=0 */
   'M','B','O','X','\0',
   /* 121. [1505]+22 mimetypes-load-control, binary=0 */
   'm','i','m','e','t','y','p','e','s','-','l','o','a','d','-','c','o','n','t','r','o','l','\0',
   /* 122. [1528]+13 NAIL_EXTRA_RC, binary=0 */
   'N','A','I','L','_','E','X','T','R','A','_','R','C','\0',
   /* 123. [1542]+9 NAIL_HEAD, binary=0 */
   'N','A','I','L','_','H','E','A','D','\0',
   /* 124. [1552]+13 NAIL_HISTFILE, binary=0 */
   'N','A','I','L','_','H','I','S','T','F','I','L','E','\0',
   /* 125. [1566]+13 NAIL_HISTSIZE, binary=0 */
   'N','A','I','L','_','H','I','S','T','S','I','Z','E','\0',
   /* 126. [1580]+9 NAIL_TAIL, binary=0 */
   'N','A','I','L','_','T','A','I','L','\0',
   /* 127. [1590]+10 newfolders, binary=0 */
   'n','e','w','f','o','l','d','e','r','s','\0',
   /* 128. [1601]+7 newmail, binary=0 */
   'n','e','w','m','a','i','l','\0',
   /* 129. [1609]+12 ORGANIZATION, binary=0 */
   'O','R','G','A','N','I','Z','A','T','I','O','N','\0',
   /* 130. [1622]+5 PAGER, binary=0 */
   'P','A','G','E','R','\0',
   /* 131. [1628]+14 pop3-keepalive, binary=0 */
   'p','o','p','3','-','k','e','e','p','a','l','i','v','e','\0',
   /* 132. [1643]+6 prompt, binary=0 */
   'p','r','o','m','p','t','\0',
   /* 133. [1650]+5 quote, binary=0 */
   'q','u','o','t','e','\0',
   /* 134. [1656]+10 quote-fold, binary=0 */
   'q','u','o','t','e','-','f','o','l','d','\0',
   /* 135. [1667]+6 record, binary=0 */
   'r','e','c','o','r','d','\0',
   /* 136. [1674]+7 replyto, binary=0 */
   'r','e','p','l','y','t','o','\0',
   /* 137. [1682]+6 screen, binary=0 */
   's','c','r','e','e','n','\0',
   /* 138. [1689]+12 sendcharsets, binary=0 */
   's','e','n','d','c','h','a','r','s','e','t','s','\0',
   /* 139. [1702]+6 sender, binary=0 */
   's','e','n','d','e','r','\0',
   /* 140. [1709]+8 sendmail, binary=0 */
   's','e','n','d','m','a','i','l','\0',
   /* 141. [1718]+17 sendmail-progname, binary=0 */
   's','e','n','d','m','a','i','l','-','p','r','o','g','n','a','m','e','\0',
   /* 142. [1736]+5 SHELL, binary=0 */
   'S','H','E','L','L','\0',
   /* 143. [1742]+4 Sign, binary=0 */
   'S','i','g','n','\0',
   /* 144. [1747]+4 sign, binary=0 */
   's','i','g','n','\0',
   /* 145. [1752]+9 signature, binary=0 */
   's','i','g','n','a','t','u','r','e','\0',
   /* 146. [1762]+12 smime-ca-dir, binary=0 */
   's','m','i','m','e','-','c','a','-','d','i','r','\0',
   /* 147. [1775]+13 smime-ca-file, binary=0 */
   's','m','i','m','e','-','c','a','-','f','i','l','e','\0',
   /* 148. [1789]+13 smime-crl-dir, binary=0 */
   's','m','i','m','e','-','c','r','l','-','d','i','r','\0',
   /* 149. [1803]+14 smime-crl-file, binary=0 */
   's','m','i','m','e','-','c','r','l','-','f','i','l','e','\0',
   /* 150. [1818]+15 smime-sign-cert, binary=0 */
   's','m','i','m','e','-','s','i','g','n','-','c','e','r','t','\0',
   /* 151. [1834]+24 smime-sign-include-certs, binary=0 */
   's','m','i','m','e','-','s','i','g','n','-','i','n','c','l','u','d','e','-','c','e','r','t','s','\0',
   /* 152. [1859]+4 smtp, binary=0 */
   's','m','t','p','\0',
   /* 153. [1864]+9 smtp-auth, binary=0 */
   's','m','t','p','-','a','u','t','h','\0',
   /* 154. [1874]+18 smtp-auth-password, binary=0 */
   's','m','t','p','-','a','u','t','h','-','p','a','s','s','w','o','r','d','\0',
   /* 155. [1893]+14 smtp-auth-user, binary=0 */
   's','m','t','p','-','a','u','t','h','-','u','s','e','r','\0',
   /* 156. [1908]+13 smtp-hostname, binary=0 */
   's','m','t','p','-','h','o','s','t','n','a','m','e','\0',
   /* 157. [1922]+12 spam-command, binary=0 */
   's','p','a','m','-','c','o','m','m','a','n','d','\0',
   /* 158. [1935]+9 spam-host, binary=0 */
   's','p','a','m','-','h','o','s','t','\0',
   /* 159. [1945]+12 spam-maxsize, binary=0 */
   's','p','a','m','-','m','a','x','s','i','z','e','\0',
   /* 160. [1958]+9 spam-port, binary=0 */
   's','p','a','m','-','p','o','r','t','\0',
   /* 161. [1968]+11 spam-socket, binary=0 */
   's','p','a','m','-','s','o','c','k','e','t','\0',
   /* 162. [1980]+9 spam-user, binary=0 */
   's','p','a','m','-','u','s','e','r','\0',
   /* 163. [1990]+10 ssl-ca-dir, binary=0 */
   's','s','l','-','c','a','-','d','i','r','\0',
   /* 164. [2001]+11 ssl-ca-file, binary=0 */
   's','s','l','-','c','a','-','f','i','l','e','\0',
   /* 165. [2013]+8 ssl-cert, binary=0 */
   's','s','l','-','c','e','r','t','\0',
   /* 166. [2022]+15 ssl-cipher-list, binary=0 */
   's','s','l','-','c','i','p','h','e','r','-','l','i','s','t','\0',
   /* 167. [2038]+11 ssl-crl-dir, binary=0 */
   's','s','l','-','c','r','l','-','d','i','r','\0',
   /* 168. [2050]+12 ssl-crl-file, binary=0 */
   's','s','l','-','c','r','l','-','f','i','l','e','\0',
   /* 169. [2063]+7 ssl-key, binary=0 */
   's','s','l','-','k','e','y','\0',
   /* 170. [2071]+10 ssl-method, binary=0 */
   's','s','l','-','m','e','t','h','o','d','\0',
   /* 171. [2082]+12 ssl-rand-egd, binary=0 */
   's','s','l','-','r','a','n','d','-','e','g','d','\0',
   /* 172. [2095]+13 ssl-rand-file, binary=0 */
   's','s','l','-','r','a','n','d','-','f','i','l','e','\0',
   /* 173. [2109]+10 ssl-verify, binary=0 */
   's','s','l','-','v','e','r','i','f','y','\0',
   /* 174. [2120]+10 stealthmua, binary=0 */
   's','t','e','a','l','t','h','m','u','a','\0',
   /* 175. [2131]+8 toplines, binary=0 */
   't','o','p','l','i','n','e','s','\0',
   /* 176. [2140]+10 ttycharset, binary=0 */
   't','t','y','c','h','a','r','s','e','t','\0',
   /* 177. [2151]+6 VISUAL, binary=0 */
   'V','I','S','U','A','L','\0',
};

static struct var_map const _var_map[] = {
   /* ok_b_add_file_recipients */ {3722159545u, 0u, 1, 0},
   /* ok_b_allnet */ {3928217024u, 20u, 1, 0},
   /* ok_b_append */ {3933094936u, 27u, 1, 0},
   /* ok_b_ask */ {109535u, 34u, 1, 0},
   /* ok_b_askatend */ {437227595u, 38u, 1, 0},
   /* ok_b_askattach */ {1544133716u, 47u, 1, 0},
   /* ok_b_askbcc */ {3936469383u, 57u, 1, 0},
   /* ok_b_askcc */ {119286981u, 64u, 1, 0},
   /* ok_b_asksign */ {1055088464u, 70u, 1, 0},
   /* ok_b_asksub */ {3936488489u, 78u, 1, 0},
   /* ok_b_attachment_ask_content_description */ {1653823630u, 85u, 1, 0},
   /* ok_b_attachment_ask_content_disposition */ {2717622527u, 120u, 1, 0},
   /* ok_b_attachment_ask_content_id */ {1759766423u, 155u, 1, 0},
   /* ok_b_attachment_ask_content_type */ {830642604u, 181u, 1, 0},
   /* ok_b_autocollapse */ {2551200844u, 209u, 1, 0},
   /* ok_b_autoprint */ {163072614u, 222u, 1, 0},
   /* ok_b_autothread */ {1231424433u, 232u, 1, 0},
   /* ok_b_bang */ {3631192u, 243u, 1, 0},
   /* ok_b_batch_exit_on_error */ {625280330u, 248u, 1, 0},
   /* ok_b_bsdannounce */ {170960u, 268u, 1, 0},
   /* ok_b_bsdcompat */ {3120210877u, 280u, 1, 0},
   /* ok_b_bsdflags */ {4132654694u, 290u, 1, 0},
   /* ok_b_bsdheadline */ {2716084787u, 299u, 1, 0},
   /* ok_b_bsdmsgs */ {2338050259u, 311u, 1, 0},
   /* ok_b_bsdorder */ {4143546805u, 319u, 1, 0},
   /* ok_b_bsdset */ {3975371813u, 328u, 1, 0},
   /* ok_b_colour_disable */ {482327989u, 335u, 1, 0},
   /* ok_b_debug */ {122332423u, 350u, 1, 1},
   /* ok_b_disconnected */ {989496243u, 356u, 1, 0},
   /* ok_b_dot */ {112679u, 369u, 1, 0},
   /* ok_b_editalong */ {3877730807u, 373u, 1, 0},
   /* ok_b_editheaders */ {1055429730u, 383u, 1, 0},
   /* ok_b_emptybox */ {171820376u, 395u, 1, 0},
   /* ok_b_emptystart */ {2449114909u, 404u, 1, 0},
   /* ok_b_flipr */ {124963293u, 415u, 1, 0},
   /* ok_b_forward_as_attachment */ {2102400300u, 421u, 1, 0},
   /* ok_b_fullnames */ {3777473511u, 443u, 1, 0},
   /* ok_b_header */ {4193457129u, 453u, 1, 1},
   /* ok_b_hold */ {3861991u, 460u, 1, 0},
   /* ok_b_idna_disable */ {2723216029u, 465u, 1, 0},
   /* ok_b_ignore */ {4235443940u, 478u, 1, 0},
   /* ok_b_ignoreeof */ {4097949886u, 485u, 1, 0},
   /* ok_b_imap_use_starttls */ {1934791407u, 495u, 1, 0},
   /* ok_b_keep */ {3958693u, 513u, 1, 0},
   /* ok_b_keep_content_length */ {3727474588u, 518u, 1, 0},
   /* ok_b_keepsave */ {302149108u, 538u, 1, 0},
   /* ok_b_line_editor_disable */ {4215099357u, 547u, 1, 0},
   /* ok_b_markanswered */ {2312309028u, 567u, 1, 0},
   /* ok_b_message_id_disable */ {130334368u, 580u, 1, 0},
   /* ok_b_metoo */ {133025124u, 599u, 1, 0},
   /* ok_b_mime_allow_text_controls */ {3414355303u, 605u, 1, 0},
   /* ok_b_mime_counter_evidence */ {3192709189u, 630u, 1, 0},
   /* ok_b_outfolder */ {1400017300u, 652u, 1, 0},
   /* ok_b_page */ {4134077u, 662u, 1, 0},
   /* ok_b_piperaw */ {2861320984u, 667u, 1, 0},
   /* ok_b_pop3_bulk_load */ {275342634u, 675u, 1, 0},
   /* ok_b_pop3_no_apop */ {3632267817u, 690u, 1, 0},
   /* ok_b_pop3_use_starttls */ {43237290u, 703u, 1, 0},
   /* ok_b_print_all_chars */ {1156901649u, 721u, 1, 0},
   /* ok_b_print_alternatives */ {1388395788u, 737u, 1, 0},
   /* ok_b_quiet */ {138331496u, 756u, 1, 0},
   /* ok_b_quote_as_attachment */ {3820786885u, 762u, 1, 0},
   /* ok_b_recipients_in_cc */ {682388781u, 782u, 1, 0},
   /* ok_b_record_resent */ {3191066333u, 799u, 1, 0},
   /* ok_b_reply_in_same_charset */ {3710195994u, 813u, 1, 0},
   /* ok_b_Replyall */ {418925029u, 835u, 1, 0},
   /* ok_b_rfc822_body_from_ */ {145783858u, 844u, 1, 0},
   /* ok_b_save */ {4242383u, 862u, 1, 0},
   /* ok_b_searchheaders */ {2344495826u, 867u, 1, 0},
   /* ok_b_sendcharsets_else_ttycharset */ {259282709u, 881u, 1, 0},
   /* ok_b_sendwait */ {2285407359u, 910u, 1, 0},
   /* ok_b_showlast */ {1926116885u, 919u, 1, 0},
   /* ok_b_showname */ {1926188546u, 928u, 1, 0},
   /* ok_b_showto */ {333061220u, 937u, 1, 0},
   /* ok_b_skipemptybody */ {3875901652u, 944u, 1, 1},
   /* ok_b_smime_force_encryption */ {3116904399u, 958u, 1, 0},
   /* ok_b_smime_no_default_ca */ {3384448360u, 981u, 1, 0},
   /* ok_b_smime_sign */ {105885657u, 1001u, 1, 0},
   /* ok_b_smtp_use_starttls */ {1310886988u, 1012u, 1, 0},
   /* ok_b_ssl_no_default_ca */ {1961350591u, 1030u, 1, 0},
   /* ok_b_ssl_v2_allow */ {1939207059u, 1048u, 1, 0},
   /* ok_b_v15_compat */ {2303937485u, 1061u, 1, 0},
   /* ok_b_verbose */ {1865913974u, 1072u, 1, 1},
   /* ok_b_writebackedited */ {3469190955u, 1080u, 1, 0},
   /* ok_v_attrlist */ {2100791799u, 1096u, 0, 0},
   /* ok_v_autobcc */ {1143881025u, 1105u, 0, 0},
   /* ok_v_autocc */ {3939178815u, 1113u, 0, 0},
   /* ok_v_autosort */ {3388960065u, 1120u, 0, 0},
   /* ok_v_charset_7bit */ {358823789u, 1129u, 0, 0},
   /* ok_v_charset_8bit */ {358859726u, 1142u, 0, 0},
   /* ok_v_cmd */ {111508u, 1155u, 0, 0},
   /* ok_v_colour_pagers */ {4118541667u, 1159u, 0, 0},
   /* ok_v_colour_from_ */ {2846725972u, 1173u, 0, 0},
   /* ok_v_colour_header */ {3809985066u, 1186u, 0, 0},
   /* ok_v_colour_msginfo */ {3893028372u, 1200u, 0, 0},
   /* ok_v_colour_partinfo */ {1593971076u, 1215u, 0, 0},
   /* ok_v_colour_terms */ {2862864972u, 1231u, 0, 0},
   /* ok_v_colour_uheader */ {906710655u, 1244u, 0, 0},
   /* ok_v_colour_user_headers */ {1414874633u, 1259u, 0, 0},
   /* ok_v_crt */ {111689u, 1279u, 0, 0},
   /* ok_v_datefield */ {3657134018u, 1283u, 0, 0},
   /* ok_v_datefield_markout_older */ {2384089013u, 1293u, 0, 0},
   /* ok_v_DEAD */ {2521070u, 1317u, 0, 0},
   /* ok_v_EDITOR */ {2783702311u, 1322u, 0, 0},
   /* ok_v_encoding */ {947851527u, 1329u, 0, 0},
   /* ok_v_escape */ {4092722801u, 1338u, 0, 0},
   /* ok_v_folder */ {4127440860u, 1345u, 0, 1},
   /* ok_v_folder_hook */ {3184215642u, 1352u, 0, 0},
   /* ok_v_from */ {3793492u, 1364u, 0, 0},
   /* ok_v_fwdheading */ {1142629489u, 1369u, 0, 0},
   /* ok_v_headline */ {1124823322u, 1380u, 0, 0},
   /* ok_v_hostname */ {1878076063u, 1389u, 0, 0},
   /* ok_v_imap_auth */ {2458536262u, 1398u, 0, 0},
   /* ok_v_imap_cache */ {3823920008u, 1408u, 0, 0},
   /* ok_v_imap_keepalive */ {75507402u, 1419u, 0, 0},
   /* ok_v_imap_list_depth */ {270835474u, 1434u, 0, 0},
   /* ok_v_indentprefix */ {1578583856u, 1450u, 0, 0},
   /* ok_v_line_editor_cursor_right */ {1667489426u, 1463u, 0, 1},
   /* ok_v_LISTER */ {3063938707u, 1488u, 0, 0},
   /* ok_v_MAIL */ {2840419u, 1495u, 0, 0},
   /* ok_v_MBOX */ {2841718u, 1500u, 0, 0},
   /* ok_v_mimetypes_load_control */ {1028657528u, 1505u, 0, 0},
   /* ok_v_NAIL_EXTRA_RC */ {4280681563u, 1528u, 0, 0},
   /* ok_v_NAIL_HEAD */ {639934357u, 1542u, 0, 0},
   /* ok_v_NAIL_HISTFILE */ {1058233243u, 1552u, 0, 0},
   /* ok_v_NAIL_HISTSIZE */ {1058700886u, 1566u, 0, 0},
   /* ok_v_NAIL_TAIL */ {640361517u, 1580u, 0, 0},
   /* ok_v_newfolders */ {985178617u, 1590u, 0, 0},
   /* ok_v_newmail */ {130414157u, 1601u, 0, 0},
   /* ok_v_ORGANIZATION */ {1265947381u, 1609u, 0, 0},
   /* ok_v_PAGER */ {97289263u, 1622u, 0, 0},
   /* ok_v_pop3_keepalive */ {1495995749u, 1628u, 0, 0},
   /* ok_v_prompt */ {227503234u, 1643u, 0, 0},
   /* ok_v_quote */ {138338510u, 1650u, 0, 0},
   /* ok_v_quote_fold */ {1182381408u, 1656u, 0, 0},
   /* ok_v_record */ {289928031u, 1667u, 0, 0},
   /* ok_v_replyto */ {993007855u, 1674u, 0, 0},
   /* ok_v_screen */ {327219328u, 1682u, 0, 0},
   /* ok_v_sendcharsets */ {1707020871u, 1689u, 0, 0},
   /* ok_v_sender */ {329446337u, 1702u, 0, 0},
   /* ok_v_sendmail */ {2285047981u, 1709u, 0, 0},
   /* ok_v_sendmail_progname */ {4267157331u, 1718u, 0, 0},
   /* ok_v_SHELL */ {101096632u, 1736u, 0, 0},
   /* ok_v_Sign */ {3100625u, 1742u, 0, 0},
   /* ok_v_sign */ {4250609u, 1747u, 0, 0},
   /* ok_v_signature */ {994697266u, 1752u, 0, 0},
   /* ok_v_smime_ca_dir */ {3002585464u, 1762u, 0, 0},
   /* ok_v_smime_ca_file */ {301144281u, 1775u, 0, 0},
   /* ok_v_smime_crl_dir */ {1039105045u, 1789u, 0, 0},
   /* ok_v_smime_crl_file */ {4225767190u, 1803u, 0, 0},
   /* ok_v_smime_sign_cert */ {2215302260u, 1818u, 0, 0},
   /* ok_v_smime_sign_include_certs */ {1036659416u, 1834u, 0, 0},
   /* ok_v_smtp */ {4255396u, 1859u, 0, 0},
   /* ok_v_smtp_auth */ {3589879203u, 1864u, 0, 0},
   /* ok_v_smtp_auth_password */ {1996663907u, 1874u, 0, 0},
   /* ok_v_smtp_auth_user */ {2594939183u, 1893u, 0, 0},
   /* ok_v_smtp_hostname */ {2613227248u, 1908u, 0, 0},
   /* ok_v_spam_command */ {3457532253u, 1922u, 0, 0},
   /* ok_v_spam_host */ {3710940444u, 1935u, 0, 0},
   /* ok_v_spam_maxsize */ {2952684415u, 1945u, 0, 0},
   /* ok_v_spam_port */ {3711227907u, 1958u, 0, 0},
   /* ok_v_spam_socket */ {79825959u, 1968u, 0, 0},
   /* ok_v_spam_user */ {3711411517u, 1980u, 0, 0},
   /* ok_v_ssl_ca_dir */ {1179440559u, 1990u, 0, 0},
   /* ok_v_ssl_ca_file */ {266904560u, 2001u, 0, 0},
   /* ok_v_ssl_cert */ {3041879213u, 2013u, 0, 0},
   /* ok_v_ssl_cipher_list */ {2789248355u, 2022u, 0, 0},
   /* ok_v_ssl_crl_dir */ {1004865324u, 2038u, 0, 0},
   /* ok_v_ssl_crl_file */ {3095856397u, 2050u, 0, 0},
   /* ok_v_ssl_key */ {2825347880u, 2063u, 0, 0},
   /* ok_v_ssl_method */ {1578094240u, 2071u, 0, 0},
   /* ok_v_ssl_rand_egd */ {2083698465u, 2082u, 0, 0},
   /* ok_v_ssl_rand_file */ {42611089u, 2095u, 0, 0},
   /* ok_v_ssl_verify */ {1930241716u, 2109u, 0, 0},
   /* ok_v_stealthmua */ {4266102040u, 2120u, 0, 0},
   /* ok_v_toplines */ {2071224238u, 2131u, 0, 0},
   /* ok_v_ttycharset */ {113531019u, 2140u, 0, 0},
   /* ok_v_VISUAL */ {3455293588u, 2151u, 0, 0},
};

#define _VAR_REV_ILL         178u
#define _VAR_REV_PRIME       379u
#define _VAR_REV_LONGEST     5u
#define _VAR_REV_WRAPAROUND  0
static ui8_t const _var_revmap[_VAR_REV_PRIME] = {
   178u, 178u, 178u, 178u, 3u, 31u, 178u, 178u, 178u, 178u,
   178u, 28u, 125u, 178u, 178u, 178u, 50u, 23u, 52u, 93u,
   145u, 159u, 170u, 173u, 178u, 112u, 143u, 160u, 178u, 178u,
   178u, 19u, 65u, 63u, 146u, 178u, 21u, 56u, 43u, 62u,
   178u, 178u, 178u, 178u, 178u, 151u, 178u, 178u, 100u, 178u,
   171u, 178u, 87u, 13u, 83u, 124u, 176u, 178u, 48u, 123u,
   178u, 75u, 9u, 178u, 178u, 178u, 12u, 18u, 24u, 178u,
   178u, 46u, 178u, 178u, 178u, 2u, 45u, 178u, 178u, 178u,
   178u, 108u, 26u, 90u, 178u, 126u, 178u, 47u, 155u, 178u,
   178u, 178u, 69u, 178u, 117u, 178u, 178u, 178u, 178u, 133u,
   178u, 178u, 178u, 178u, 178u, 84u, 106u, 178u, 178u, 178u,
   178u, 178u, 178u, 44u, 178u, 178u, 29u, 122u, 178u, 172u,
   80u, 141u, 92u, 178u, 144u, 101u, 178u, 131u, 178u, 64u,
   35u, 140u, 166u, 178u, 178u, 178u, 178u, 178u, 178u, 163u,
   178u, 178u, 7u, 20u, 178u, 178u, 107u, 132u, 178u, 157u,
   178u, 97u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u,
   178u, 59u, 178u, 178u, 95u, 74u, 0u, 5u, 89u, 96u,
   178u, 34u, 98u, 178u, 178u, 178u, 178u, 178u, 178u, 115u,
   178u, 178u, 178u, 178u, 178u, 178u, 178u, 178u, 136u, 73u,
   154u, 149u, 178u, 119u, 104u, 178u, 178u, 42u, 79u, 162u,
   165u, 178u, 109u, 137u, 168u, 178u, 178u, 178u, 139u, 178u,
   178u, 91u, 57u, 110u, 129u, 39u, 178u, 70u, 8u, 36u,
   178u, 161u, 178u, 54u, 158u, 178u, 178u, 71u, 178u, 175u,
   178u, 178u, 135u, 33u, 88u, 178u, 67u, 22u, 177u, 178u,
   178u, 178u, 178u, 178u, 14u, 178u, 86u, 178u, 178u, 178u,
   178u, 178u, 178u, 164u, 94u, 178u, 178u, 72u, 41u, 37u,
   25u, 77u, 128u, 99u, 150u, 167u, 30u, 113u, 156u, 178u,
   178u, 55u, 1u, 78u, 178u, 81u, 178u, 142u, 178u, 178u,
   10u, 85u, 178u, 169u, 15u, 6u, 60u, 178u, 178u, 178u,
   178u, 178u, 178u, 49u, 178u, 178u, 178u, 178u, 178u, 153u,
   178u, 178u, 178u, 51u, 178u, 178u, 178u, 178u, 111u, 4u,
   68u, 178u, 178u, 40u, 178u, 178u, 178u, 178u, 178u, 27u,
   178u, 178u, 178u, 138u, 53u, 178u, 178u, 134u, 178u, 82u,
   178u, 178u, 127u, 178u, 178u, 178u, 61u, 178u, 178u, 178u,
   178u, 102u, 76u, 105u, 116u, 130u, 174u, 32u, 178u, 178u,
   178u, 178u, 178u, 178u, 178u, 120u, 147u, 178u, 178u, 58u,
   38u, 178u, 178u, 121u, 152u, 178u, 148u, 178u, 178u, 114u,
   178u, 66u, 17u, 16u, 11u, 103u, 178u, 118u, 178u
};
