#@ makefile.obj for SU C and C++ objects (not libraries).
#@ Needs ECHO_CC, CXX, SU_CXXFLAGS, CC, SU_CFLAGS, SU_INCS.
#@ Plus SU_INCDIR and SU_SRCDIR.

SU_CXX_OBJ = cxx-core.o

SU_C_OBJ = su-avopt.o \
	su-core-code.o su-core-errors.o \
	su-cs-alloc.o su-cs-ctype.o su-cs-find.o \
		su-cs-misc.o su-cs-tbox.o \
		su-cs-tools.o \
	su-cs-dict.o \
	su-icodec-dec.o su-icodec-enc.o \
	su-mem-alloc.o su-mem-tools.o \
	su-mem-bag.o \
	su-prime.o \
	su-utf.o

$(SU_CXX_OBJ) $(SU_C_OBJ): $(SU_INCDIR)su/code.h $(SU_INCDIR)su/config.h

su-cxx-core.o: $(SU_SRCDIR)su/cxx-core.cc \
		$(SU_INCDIR)su/cs.h $(SU_INCDIR)su/utf.h
	$(ECHO_CC)$(CXX) $(SU_CXXFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cxx-core.cc

su-avopt.o: $(SU_SRCDIR)su/avopt.c $(SU_INCDIR)su/avopt.h \
		$(SU_INCDIR)su/cs.h $(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/avopt.c

su-core-code.o: $(SU_SRCDIR)su/core-code.c \
		$(SU_INCDIR)su/icodec.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/core-code.c
su-core-errors.o: $(SU_SRCDIR)su/core-errors.c $(SU_SRCDIR)su/gen-errors.h \
		$(SU_INCDIR)su/cs.h $(SU_INCDIR)su/icodec.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/core-errors.c

su-cs-alloc.o: $(SU_SRCDIR)su/cs-alloc.c $(SU_INCDIR)su/cs.h \
		$(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-alloc.c
su-cs-ctype.o: $(SU_SRCDIR)su/cs-ctype.c $(SU_INCDIR)su/cs.h \
			$(SU_SRCDIR)su/gen-cs-ctype.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-ctype.c
su-cs-find.o: $(SU_SRCDIR)su/cs-find.c $(SU_INCDIR)su/cs.h \
		$(SU_INCDIR)su/bits.h $(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-find.c
su-cs-misc.o: $(SU_SRCDIR)su/cs-misc.c $(SU_INCDIR)su/cs.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-misc.c
su-cs-tbox.o: $(SU_SRCDIR)su/cs-tbox.c $(SU_INCDIR)su/cs.h \
		$(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-tbox.c
su-cs-tools.o: $(SU_SRCDIR)su/cs-tools.c $(SU_INCDIR)su/cs.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-tools.c

su-cs-dict.o: $(SU_SRCDIR)su/cs-dict.c $(SU_INCDIR)su/cs-dict.h \
			$(SU_SRCDIR)su/x-assoc-map.h \
		$(SU_INCDIR)su/cs.h $(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/cs-dict.c

su-icodec-dec.o: $(SU_SRCDIR)su/icodec-dec.c $(SU_INCDIR)su/icodec.h \
		$(SU_INCDIR)su/cs.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/icodec-dec.c
su-icodec-enc.o: $(SU_SRCDIR)su/icodec-enc.c $(SU_INCDIR)su/icodec.h \
		$(SU_INCDIR)su/cs.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/icodec-enc.c

su-mem-alloc.o: $(SU_SRCDIR)su/mem-alloc.c $(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/mem-alloc.c
su-mem-tools.o: $(SU_SRCDIR)su/mem-tools.c $(SU_INCDIR)su/mem.h \
			$(SU_SRCDIR)su/x-mem-tools.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/mem-tools.c

su-mem-bag.o: $(SU_SRCDIR)su/mem-bag.c $(SU_INCDIR)su/mem-bag.h \
		$(SU_INCDIR)su/mem.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/mem-bag.c

su-prime.o: $(SU_SRCDIR)su/prime.c $(SU_INCDIR)su/prime.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/prime.c

su-utf.o: $(SU_SRCDIR)su/utf.c $(SU_INCDIR)su/utf.h
	$(ECHO_CC)$(CC) $(SU_CFLAGS) $(SU_INCS) -c -o $(@) \
		$(SU_SRCDIR)su/utf.c

# s-mk-mode
