/*@ src/mx/gen-cmd-tab.h, generated by mk/make-cmd-tab.sh.
 *@ See cmd-tab.[ch] for more */

#define a_CTAB_DEFAULT_IDX 93
#define a_CTAB_COUNT 202
static u8 const a_ctab__cidx[128] = {
#define a_X a_CTAB_COUNT
   /* 0x0 */ a_X, a_X, a_X, a_X,
   /* 0x4 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x9 */ a_X, a_X, a_X, a_X, a_X,
   /* 0xE */ a_X, a_X, a_X, a_X, a_X,
   /* 0x13 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x18 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x1D */ a_X, a_X, a_X, a_X, 0,
   /* 0x22 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x27 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x2C */ a_X, a_X, a_X, a_X, a_X,
   /* 0x31 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x36 */ a_X, a_X, a_X, a_X, a_X,
   /* 0x3B */ a_X, a_X, 1, a_X, 2,
   /* 0x40 */ a_X, a_X, a_X, 21, 27,
   /* 0x45 */ a_X, 48, a_X, a_X, a_X,
   /* 0x4A */ a_X, a_X, 76, 80, 95,
   /* 0x4F */ a_X, 99, a_X, 113, 124,
   /* 0x54 */ 150, 177, a_X, a_X, a_X,
   /* 0x59 */ a_X, 200, a_X, a_X, a_X,
   /* 0x5E */ a_X, a_X, a_X, 4, 9,
   /* 0x63 */ 10, 25, 36, 49, 65,
   /* 0x68 */ 67, 72, a_X, a_X, 77,
   /* 0x6D */ 81, 93, a_X, 100, 106,
   /* 0x72 */ 107, 125, 151, 157, 190,
   /* 0x77 */ 197, 198, a_X, 201, a_X,
   /* 0x7C */ 3, a_X, a_X, a_X,
#undef a_X
};
#define a_CTAB_CIDX(C) (S(u8,C) <= 127 ? a_ctab__cidx[S(u8,C)] : a_CTAB_COUNT)
CTAV(a_CTAB_COUNT == NELEM(a_ctab_ctable));
