#@ makefile.obj for mailx C objects (not program).
#@ Requires pre-work to generate some internal headers files, noticably
#@ gen-mime-types.h.
#@ Needs ECHO_CC, CC, MX_CFLAGS, MX_INCS.
#@ Plus MX_CWDDIR, MX_INCDIR and MX_SRCDIR.

MX_C_OBJ = mx-accmacvar.o \
		mx-attachment.o \
		mx-auxlily.o \
	mx-cmd-cnd.o mx-cmd-folder.o mx-cmd-head.o mx-cmd-misc.o \
			mx-cmd-msg.o mx-cmd-resend.o mx-cmd-tab.o \
			mx-cmd-write.o \
		mx-collect.o \
		mx-colour.o \
	mx-dig-msg.o \
		mx-dotlock.o \
	mx-edit.o \
	mx-filter-html.o mx-filter-quote.o \
		mx-fio.o \
		mx-folder.o \
	mx-go.o \
	mx-header.o \
	mx-iconv.o \
		mx-ignore.o \
		mx-imap-search.o \
	mx-maildir.o \
		mx-main.o \
		mx-message.o \
		mx-mime-enc.o mx-mime-param.o mx-mime-parse.o \
			mx-mime-types.o mx-mime.o \
	mx-nam-a-grp.o \
	mx-obs-imap-cache.o mx-obs-imap.o \
		mx-obs-lzw.o \
	mx-path.o \
		mx-pop3.o \
		mx-popen.o \
	mx-quit.o \
	mx-send.o \
		mx-sendout.o \
		mx-shexp.o \
		mx-signal.o \
		mx-smtp.o \
		mx-socket.o \
		mx-spam.o \
		mx-strings.o \
	mx-termcap.o \
		mx-thread.o \
		mx-tls.o \
		mx-tty.o \
	mx-ui-str.o \
		mx-urlcrecry.o \
	mx-xtls.o

$(MX_C_OBJ): $(MX_CWDDIR)include/mx/gen-config.h \
		$(MX_CWDDIR)include/mx/config.h \
		$(MX_INCDIR)mx/nail.h $(MX_INCDIR)mx/nailfuns.h

mx-accmacvar.o: $(MX_SRCDIR)mx/accmacvar.c $(MX_SRCDIR)mx/gen-okeys.h \
			$(MX_CWDDIR)include/mx/gen-version.h \
		$(MX_INCDIR)mx/iconv.h $(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/accmacvar.c

mx-attachment.o: $(MX_SRCDIR)mx/attachment.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/attachment.c

mx-auxlily.o: $(MX_SRCDIR)mx/auxlily.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/auxlily.c

mx-cmd-cnd.o: $(MX_SRCDIR)mx/cmd-cnd.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-cnd.c
mx-cmd-folder.o: $(MX_SRCDIR)mx/cmd-folder.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-folder.c
mx-cmd-head.o: $(MX_SRCDIR)mx/cmd-head.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-head.c
mx-cmd-misc.o: $(MX_SRCDIR)mx/cmd-misc.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-misc.c
mx-cmd-msg.o: $(MX_SRCDIR)mx/cmd-msg.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-msg.c
mx-cmd-resend.o: $(MX_SRCDIR)mx/cmd-resend.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-resend.c
mx-cmd-tab.o: $(MX_SRCDIR)mx/cmd-tab.c $(MX_SRCDIR)mx/cmd-tab.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-tab.c
mx-cmd-write.o: $(MX_SRCDIR)mx/cmd-write.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/cmd-write.c

mx-collect.o: $(MX_SRCDIR)mx/collect.c \
		$(MX_INCDIR)mx/filter-quote.h $(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/collect.c

mx-colour.o: $(MX_SRCDIR)mx/colour.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/colour.c

mx-dig-msg.o: $(MX_SRCDIR)mx/dig-msg.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/dig-msg.c

mx-dotlock.o: $(MX_SRCDIR)mx/dotlock.c $(MX_SRCDIR)mx/dotlock.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/dotlock.c

mx-edit.o: $(MX_SRCDIR)mx/edit.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/edit.c

mx-filter-html.o: $(MX_SRCDIR)mx/filter-html.c $(MX_INCDIR)mx/filter-html.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/filter-html.c
mx-filter-quote.o: $(MX_SRCDIR)mx/filter-quote.c $(MX_INCDIR)mx/filter-quote.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/filter-quote.c

mx-fio.o: $(MX_SRCDIR)mx/fio.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/fio.c

mx-folder.o: $(MX_SRCDIR)mx/folder.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/folder.c

mx-go.o: $(MX_SRCDIR)mx/go.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/go.c

mx-header.o: $(MX_SRCDIR)mx/header.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/header.c

mx-iconv.o: $(MX_SRCDIR)mx/iconv.c $(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/iconv.c

mx-ignore.o: $(MX_SRCDIR)mx/ignore.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/ignore.c

mx-imap-search.o: $(MX_SRCDIR)mx/imap-search.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/imap-search.c

mx-maildir.o: $(MX_SRCDIR)mx/maildir.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/maildir.c

mx-main.o: $(MX_SRCDIR)mx/main.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/main.c

mx-message.o: $(MX_SRCDIR)mx/message.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/message.c

mx-mime-enc.o: $(MX_SRCDIR)mx/mime-enc.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/mime-enc.c
mx-mime-param.o: $(MX_SRCDIR)mx/mime-param.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/mime-param.c
mx-mime-parse.o: $(MX_SRCDIR)mx/mime-parse.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/mime-parse.c
mx-mime-types.o: $(MX_SRCDIR)mx/mime-types.c gen-mime-types.h \
		$(MX_INCDIR)mx/filter-html.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/mime-types.c
mx-mime.o: $(MX_SRCDIR)mx/mime.c \
		$(MX_INCDIR)mx/filter-quote.h $(MX_INCDIR)mx/iconv.h \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/mime.c

mx-nam-a-grp.o: $(MX_SRCDIR)mx/nam-a-grp.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/nam-a-grp.c

mx-obs-imap-cache.o: $(MX_SRCDIR)mx/obs-imap-cache.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/obs-imap-cache.c
mx-obs-imap.o: $(MX_SRCDIR)mx/obs-imap.c $(MX_SRCDIR)mx/obs-imap-gssapi.h \
		$(MX_INCDIR)mx/iconv.h $(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/obs-imap.c
mx-obs-lzw.o: $(MX_SRCDIR)mx/obs-lzw.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/obs-lzw.c

mx-path.o: $(MX_SRCDIR)mx/path.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/path.c

mx-pop3.o: $(MX_SRCDIR)mx/pop3.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/pop3.c

mx-popen.o: $(MX_SRCDIR)mx/popen.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/popen.c

mx-quit.o: $(MX_SRCDIR)mx/quit.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/quit.c

mx-send.o: $(MX_SRCDIR)mx/send.c \
		$(MX_INCDIR)mx/filter-quote.h $(MX_INCDIR)mx/iconv.h \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/send.c

mx-sendout.o: $(MX_SRCDIR)mx/sendout.c \
		$(MX_INCDIR)mx/iconv.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/sendout.c

mx-shexp.o: $(MX_SRCDIR)mx/shexp.c \
		$(MX_INCDIR)mx/iconv.h $(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/shexp.c

mx-signal.o: $(MX_SRCDIR)mx/signal.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/signal.c

mx-smtp.o: $(MX_SRCDIR)mx/smtp.c $(MX_SRCDIR)mx/smtp-gssapi.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/smtp.c

mx-socket.o: $(MX_SRCDIR)mx/socket.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/socket.c

mx-spam.o: $(MX_SRCDIR)mx/spam.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/spam.c

mx-strings.o: $(MX_SRCDIR)mx/strings.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/strings.c

mx-termcap.o: $(MX_SRCDIR)mx/termcap.c $(MX_SRCDIR)mx/gen-tcaps.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/termcap.c

mx-thread.o: $(MX_SRCDIR)mx/thread.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/thread.c

mx-tls.o: $(MX_SRCDIR)mx/tls.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/tls.c

mx-tty.o: $(MX_SRCDIR)mx/tty.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/tty.c

mx-ui-str.o: $(MX_SRCDIR)mx/ui-str.c $(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/ui-str.c

mx-urlcrecry.o: $(MX_SRCDIR)mx/urlcrecry.c \
		$(MX_INCDIR)mx/ui-str.h
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/urlcrecry.c

mx-xtls.o: $(MX_SRCDIR)mx/xtls.c
	$(ECHO_CC)$(CC) $(MX_CFLAGS) $(MX_INCS) -c -o $(@) \
		$(MX_SRCDIR)mx/xtls.c

# s-mk-mode
