#@ makefile.obj for mailx-dotlock object (not program).
#@ Needs ECHO_CC, CC, PS_DOTLOCK_CFLAGS, PS_DOTLOCK_INCS.
#@ Plus PS_DOTLOCK_CWDDIR, PS_DOTLOCK_INCDIR and PS_DOTLOCK_SRCDIR.

PS_DOTLOCK_C_OBJ = main.o

main.o: $(PS_DOTLOCK_SRCDIR)ps-dotlock/main.c \
		$(PS_DOTLOCK_CWDDIR)include/mx/gen-config.h \
		$(PS_DOTLOCK_CWDDIR)include/mx/config.h \
		$(PS_DOTLOCK_INCDIR)mx/nail.h $(PS_DOTLOCK_SRCDIR)mx/dotlock.h
	$(ECHO_CC)$(CC) $(PS_DOTLOCK_CFLAGS) $(PS_DOTLOCK_INCS) -c -o $(@) \
		$(PS_DOTLOCK_SRCDIR)ps-dotlock/main.c

# s-mk-mode
